### ISSUE TITLE
[Request] Refresh Chunks Option

### ISSUE THREAD

**Issue by CVFireDragon** [Querz/mcaselector#101]
Chunks do not display what is actually there until you refresh chunks by deleting a chunk. Can you add an option to refresh it without deleting other chunks? Thanks

**Comment by Querz** [comment]
The image generated from a region is saved in a `cache` folder in the same directory as the program. Loading an image from the cache is way faster than generating it every time that region moves into view (a few milliseconds to load the image vs 0.5-6 seconds for generating the image from the region file).

There are 3 options to selectively reset the cache files:
* `View --> Clear cache` (deletes cache files for all regions that are currently visible in the window)
* `View --> Clear all cache` (deletes all cache files for this world)
* `Selection --> Clear cache` (deletes all cache files of regions that have at least 1 chunk selected)
