### ISSUE TITLE
[Request] Skip validation of biome name as with Palette

### ISSUE THREAD

**Issue by kgibson9489** [Querz/mcaselector#102]
If it doesn't already exist, could you implement a validation free search syntax for biomes like how Palette uses single quotes to skip validation? I am trying to find specific biomes related to a mod and being able to search for them instead of the numerous blocks would be a huge help

Running mcaselector-1.9.10

**Comment by Querz** [comment]
Good point! This feature will be available in the next release, [the code is already done](https://github.com/Querz/mcaselector/commit/817b40ef4387c219e4119ea1850a9455ff8ec449).
You will be able to use Biome names, Biome IDs and Biome IDs for custom Biomes quoted in single quotes, just like with the Palette.

**Comment by Querz** [comment]
See [release 1.9.11](https://github.com/Querz/mcaselector/releases/latest)

**Comment by kgibson9489** [comment]
@Querz Thanks for the fast response! Sorry to bring this back up, but it looks like the form is still trying to validate the biome even with single quotes:

![image](https://user-images.githubusercontent.com/2601045/81481992-d686c300-9201-11ea-9ee8-a38200e711fe.png)

**Comment by Querz** [comment]
Biomes are actually saved using IDs, not their names. Using the names in MCA Selector is only for convenience. There is no way to know what kind of custom biomes there are in your world. You will need to find the biome's ID, and then use it in the filter with single quotes.
Example:
```
plains,14,'123'
```
would search for Plains, Mushroom Field, and your custom biome with ID 123.
