### ISSUE TITLE
Y Chunk Support?

### ISSUE THREAD

**Issue by instantout** [Querz/mcaselector#103]
Excuse me this is the only way to add an idea.
Anyways Support for the Y Chunks they range from 0-15
The Idea behind this is so when updating to new versions or lets just say you want to delete a cave system it would be possible Under Y(Chunk)

I believe Minecraft added the Y chunks in 1.12+

The whole idea is just to be able to Delete or Import/export Specific Y Chunks after clicking them.

Anyways thank you for reading,
NBT = Minecraft Wiki it's under "Sections" for Chunk format.

**Comment by Querz** [comment]
This is partially possible, BUT the entire generation process depends on the `Status` (See [chunk format](https://minecraft.gamepedia.com/Chunk_format) --> Status) which is on chunk level, not on section level. Usually the `Status` is set to "full", which means that all generation has finished for this chunk (terrain generation, cave carving, structures, biomes, liquids, etc).

In order for Minecraft to generate new terrain, along the sections being deleted, the `Status` has to be set to "empty". This results in ALL sections to be regenerated, not just missing ones. If you made changes to a section, they are overwritten by the Minecraft generator.

Example:
This mountain is mostly in Section Y=5, just the peak is in Y=6.
![2020-05-12_11 16 08](https://user-images.githubusercontent.com/8278330/81667272-5d76ae00-9443-11ea-8b93-4f36c62dee93.png)
Now I make some changes in Y=5 (yellow) as well as in Y=6 (blue).
![2020-05-12_11 17 25](https://user-images.githubusercontent.com/8278330/81667067-1f798a00-9443-11ea-87e7-7f9774be5e42.png)
I want to regenerate everything in Y=5, so I delete the section using the NBT Editor and set the `Status` to "empty". Opening the world in Minecraft shows this:
![2020-05-12_11 20 02](https://user-images.githubusercontent.com/8278330/81667431-8c8d1f80-9443-11ea-934e-84b5c8a74041.png)
It did indeed regenerate Y=5, BUT it also generated new terrain in Y=6 overwriting some of our structures.

I imagine that this might work if you have e.g. a mob farm high above ground, with no village or any other structure that depends on the height of the terrain nearby, but not if you altered the terrain in any way.

**Comment by Querz** [comment]
This might actually be useful for the Nether, if you built stuff above Y=128. Maybe I can add a parameter to headless mode, because this will be pretty unpredictable if you don't know what you're doing.

**Comment by Querz** [comment]
@instantout the `DeleteSections` field in the NBT Changer will support a comma separated list of ranges that should be deleted.
Examples:
* `5` will delete all sections with Y=5.
* `0:7` will delete all sections ranging from Y=0 to Y=7, inclusive.
* `:7,9:` will delete all sections, except Y=8.
* `true` or `:` will delete all sections.
In combination with `Status` set to `empty`, this could be used to regenerate the Nether while preserving builds above 128.

If you want to try it, here's a compiled version of the current status of the master branch:
[mcaselector-1.10.1-pre.jar.zip](https://github.com/Querz/mcaselector/files/4702789/mcaselector-1.10.1-pre.jar.zip)

**Comment by Querz** [comment]
Forgot about importing / exporting, so i'm reopening this issue :)

**Comment by Querz** [comment]
Implemented Selection range import in release [1.11](https://github.com/Querz/mcaselector/releases/tag/1.11).
