### ISSUE TITLE
Request: option to reorder filter conditions by dragging

### ISSUE THREAD

**Issue by Artoria2e5** [Querz/mcaselector#105]
**Describe the bug**
It would be helpful to allow people to reorder filter conditions by simply dragging them around. The UI can also be made a bit less confusing by putting the logical operator at the first column while we are at it.

**To Reproduce**
1. Open any world.
2. Tools → Filter Chunks...
3. Add a filter
4. Mess up its position because logical operators matter

**Expected behavior**
Some easy way to recover from this situation because brains are error-prone.

**Environment (please complete the following information):**
- OS: macOS
- Java version: build 14+36-1461
- Version: 1.9.11

**Comment by Querz** [comment]
I'm working on adding a decent drag-and-drop mechanic to the filters, similar to the NBT-Editor.

**Comment by Querz** [comment]
I added the drag-and-drop mechanic in the [latest release](https://github.com/Querz/mcaselector/releases/latest).
