### ISSUE TITLE
Request: export / import textual query in the GUI

### ISSUE THREAD

**Issue by Artoria2e5** [Querz/mcaselector#106]
**Describe the bug**
The "filter chunks" function can benefit from an option to import and export queries in the textual form, probably the `--query` thing. This would allow tutorials to be written easier and people to reuse some complex megaueries.

**To Reproduce**
1. Wait for Mojang to add some new worldgen feature
2. Open a world
3. Compose a query that supposedly protects your craft and includes the stuff to be updated
4. Oops, you can't save it unless you do a screenshot!

**Expected behavior**

**Screenshots and other files**
Relevant world files ('.mca'-files) and selection files ('.csv'.files) must be bundled in a '.zip'-archive.
To create the 'debug.log' file, follow these steps:
1. Enable 'Print debug messages' in 'File'-->'Settings'.
2. Restart MCA Selector.
3. Reproduce the problem.
4. Close MCA Selector and attach the 'debug.log' file to this bug report.

**Expected behavior**
Some easy way to save a query.

**Environment (please complete the following information):**
- OS: macOS
- Java version: build 14+36-1461
- Version: 1.9.11

**Comment by Querz** [comment]
A text field below the filter window that updates when changes are made to the filters as well as updates the filters when changes are made to the query will be in the next release.

**Comment by Querz** [comment]
Added in the [latest release](https://github.com/Querz/mcaselector/releases/latest).
