### ISSUE TITLE
[Suggestion] Can we be able to move around the map without the goto command

### ISSUE THREAD

**Issue by mcdodge34** [Querz/mcaselector#11]
Just discovered this tool, it will be extremely helpful to regenerate the villages on our private family server map once they release the 1.14.1 corrected version, but there's just too much of hassle to remember the coordinates of everything cause right now we have to use the goto to center on it, or maybe I didn't understand how to move otherwise, it would be much simpler if we could move around the map like on google map or with the arrow keys so we could center on the stuff we want manually and delete the chunks we want quicker.

**Comment by AJMFactsheets** [comment]
If you use the middle mouse button, then you can drag the map around like on google maps. Hope this helps!

**Comment by marcopixel** [comment]
I think adding the arrow keys to move around could be added as a additional way to move around, because there might be some people with no or a broken mouse wheel.

**Comment by mcdodge34** [comment]
This is literally the only thing I didn't think of trying to move around with the middle mouse button, I'm not used at this button yet, thanks, consider this thread closed for now

**Comment by Querz** [comment]
[Release 1.7](https://github.com/Querz/mcaselector/releases/tag/1.7) adds support for moving the map using WASD. Hold the Shift key to double the speed.
