### ISSUE TITLE
Chunk selection filter  freezes near end of job and does not complete

### ISSUE THREAD

**Issue by NeonRexodus** [Querz/mcaselector#119]
Chunk selector freezes near end of job, leading to noncompletion. Even when using no custom filters, just the default ones.

**To Reproduce**
1. Open Minecraft 1.16.1 and make a new world. Explore a bit and generate some extra chunks.

2. Open MCAFilter 1.11.1 and open the world you just generated.
3. Tools>Filter
4. See that it starts selecting chunks very quick, but then also slows down and freezes quickly too.

**Expected behavior**
When the Filter is used, it is expected the chunks will be selected in realtime with no freezing.

**Screenshots and other files**

![example](https://user-images.githubusercontent.com/34557216/85586604-af941d00-b606-11ea-8914-2df216d9a97d.jpg)
![stuck like this](https://user-images.githubusercontent.com/34557216/85586609-b02cb380-b606-11ea-8999-33a838b223d3.jpg)

Edit: Added Debug log 
[debug.log](https://github.com/Querz/mcaselector/files/4826881/debug.log)

There is a filesize limit that makes it impossible to effectively send the amount of affected region files.

**Environment (please complete the following information):**
- OS: Windows 10
- Java version: (build 1.8.0_241-b07)
- Version: 1.11.1

**Additional context**
Add any other context about the problem here, e.g.:
- Minecraft version used to generate affected parts of your world: 1.16.1

**Comment by Querz** [comment]
How much RAM do you have and how much did you assign to MCA Selector?
Enable "Print debug messages" in the settings, reproduce the issue, close the program and look into the generated `debug.log` file. At the top there's a line starting with `jvm.max.mem`, what number does it show there?

**Comment by NeonRexodus** [comment]
> How much RAM do you have and how much did you assign to MCA Selector?
> Enable "Print debug messages" in the settings, reproduce the issue, close the program and look into the generated `debug.log` file. At the top there's a line starting with `jvm.max.mem`, what number does it show there?

I added the debug.log. it appears a possible resources leak ? I sent the whole debug file, I had included that with the world files and had forgotten to send it when I realized the affected .mca files were too many to send.

**Comment by NeonRexodus** [comment]
This is such a wonderful program, I hope this bug report helps improvements~ Thank you for making it.

**Comment by Querz** [comment]
You are running out of memory. You can try turning all the sliders in the settings to the left, otherwise it will try to open and parse 12 mca files at once, one on each processor core. I'll try to tweak this a little bit better so it automatically turns the settings down depending on your hardware.

I have to admit I never tested it with less than 4GB :)

**Comment by NeonRexodus** [comment]
welp, with that, you literally helped me figure out that I had installed the 32bit version by accident. Closing issue for now until further notice.
