### ISSUE TITLE
App freezing while applying filters

### ISSUE THREAD

**Issue by SIDDHARTH2595** [Querz/mcaselector#121]
![image](https://user-images.githubusercontent.com/14028163/85932244-f7a58f00-b8e7-11ea-975d-f9ca97f0327d.png)

I am trying to select overworld chunks with filter - "InhabitedTime < 10 min". Process gets frozen in above state. I have let it sit for more than an hour with no progess in "selected" chunks.
Minecraft save version - 1.16.1 (~400mb)
MCA selector version - 1.11.1

**Comment by Querz** [comment]
Make sure you are using 64bit Java, not 32bit and assign enough RAM (2GB-4GB).
