### ISSUE TITLE
Unable to Open MCASelector with recommended Java versions

### ISSUE THREAD

**Issue by SSH3R0** [Querz/mcaselector#123]
I had downloaded the proper Java files, alongside the MCA program, and attmpted to run. No window pop up. Attempted the run command, saw the window popup in the windows task bar, just to see it close itself a second later. I dont receive any visual error from Windows or Java, so I'm not sure what exactly I need to do right or what I am doing wrong.

Windows 10
Java 1.8.0_251
MInecraft Version 1.15.2

**Comment by Querz** [comment]
Can you run it from the console please and look for any error?

**Comment by Shyguy11** [comment]
I have the same problem but with Minecraft 1.16.1, when running java -jar mcaselector-1.12.jar on the console i get 
"Error: Unable to access jarfile mcaselector-1.12.jar". Nothing on the internet that I've found seems to be able to solve this. Thanks

**Comment by Querz** [comment]
Assuming you are also running Windows 10, did you navigate to the folder where the mcaselector-1.12.jar file is located and then executed the command?

**Comment by SSH3R0** [comment]
I am unsure as what command to run in the console, since I have very minor expirience of using it. I had just recently downloaded the the 1.12 update for MCA selector, and now it says I need JAVA FX 14.0.1. I had downloaded it and put it within the java folder, but it still gives me the same error. @Querz, what do I need to do to fix this?

**Comment by Querz** [comment]
I added step-by-step instructions to the Readme for when JavaFX is not installed, I hope this helps.
