### ISSUE TITLE
Copying chunks doesnt copy chest contents

### ISSUE THREAD

**Issue by lillodaniel** [Querz/mcaselector#128]
Im having some issues copying structures and the chests within them. Whenever i use the new command (Ctrl C/Ctrl V)it copies them empty and transparent. When using the import/export method i have problems with 2 structures copying either incomplete or just skipping the copy completely with no effect on the new map.

**Comment by Querz** [comment]
Thanks for pointing this out, this is actually a bug affecting TileEntities and Entities. They are not imported correctly when an offset is applied while importing them into a world.

I wrote a fix that will be in the next release soon.

**Comment by Querz** [comment]
Fixed in [release 1.12.1](https://github.com/Querz/mcaselector/releases/tag/1.12.1)
