### ISSUE TITLE
Option to prune maps

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [Querz/mcaselector#13]
There should be a feature to prune the map. Meaning after you select all the chunks you want to keep, you should be able to go to Selection > Prune Chunks and it should delete all chunks that aren't selected in your selection

**Comment by Querz** [comment]
You can achieve this by exporting the selected chunks to a new folder via `Selection` --> `Export selected chunks` which leaves you only with the chunks you selected.

**Comment by BennyDoesTheStuff** [comment]
ahh yeah didn't think of that, thank you!!
