### ISSUE TITLE
Incomplete Process

### ISSUE THREAD

**Issue by LucidAPs** [Querz/mcaselector#130]
Windows 10 java 8
MCA version 1.12.1
Minecraft 1.16

There are some regions that are particularly busy (block type wise) that  i can't export or copy paste. The export process just hangs and never finishes with no errors and the copy paste faction just doesn't paste all the blocks.

**Comment by Querz** [comment]
Make sure that you are using 64bit Java, as 32bit Java might only set the maximum allocated memory to a very low value. You can also try to turn all the sliders in the Settings to the left, so it doesn't process too many files at once.

**Comment by DmitryRendov** [comment]
Try to allocate more memory as well. up to 10-16GB
