### ISSUE TITLE
Option to copy biome data between worlds

### ISSUE THREAD

**Issue by zachman42** [Querz/mcaselector#132]
I have a world I converted from bedrock and the ocean biomes got screwed up. When the converter gets patched, rather than reconverting the world and losing my progress or changing entire chunks' biome data, I would like to copy it from the fixed world over to the flawed one to save time and accuracy.

**Comment by Querz** [comment]
You can use the Chunk Filter to select all ocean biomes in your fixed world, then copy and paste them into your broken world.
Have a look at
* [Chunk filter](https://github.com/Querz/mcaselector#chunk-filter)
* [Chunk import](https://github.com/Querz/mcaselector#chunk-import)
* [Copy+Paste](https://github.com/Querz/mcaselector#copy-and-paste)

**Comment by zachman42** [comment]
That's not a bad solution, but it will overwrite all the work I have done since in those biomes.

**Comment by Querz** [comment]
You can either adjust the filter so it does not select chunks that you worked on (e.g. by specifying a block that you used in those chunks) or you can manually deselect those chunks after applying the filter.
When you start the chunk import, select the `Apply to selection only` option when you import those chunks.

**Comment by zachman42** [comment]
This option will work, I appreciate your help.
