### ISSUE TITLE
JavaFX error and Fixes

### ISSUE THREAD

**Issue by Endertainer** [Querz/mcaselector#137]
So I got this error when I tried to run MCAselector. It has something to do with java fx. At first, I don't know what to do and how to fix it. So I follow the guide to fix this issue and it works. But the thing that's bothering me is that you need to use PowerShell every time you want to run the app. So my fix for this is to make a batch file. First, put the java fx folder and MCAselector in the documents or any directory that you want. Then just follow the instruction on how to fix java fx error. in the java fx folder, hold `Shift` and Right-click on an empty space in that folder and select `Open PowerShell window here` (`Open Command window here` on Windows 8 and earlier). Type ` java --module-path` (with space at the end), then drag and drop the `lib`-folder into the console. Continue to type `--add-modules ALL-MODULE-PATH -jar` (with space at the beginning and the end), then drag and drop the `MCAselector.jar` into the console and hit Enter. You then should see the app running. Then. just copy the command and put it into a text file. You could name the file whatever you want, but you need to change the file extension from `.txt` to `.bat`. If you did this correctly, you should be able to run MCAselector from the batch file. I hope this could be helpful to anyone who is bothered with the error and I hope that the error could be fixed so it would be much easier for anyone to use MCAselector.

**Comment by Querz** [comment]
Thanks, I added additional instructions to the Readme.

**Comment by JaszczurK** [comment]
I CAN NOT FUCKING FIX THIS PROBLEM FUCK THIS PROGRAM
