### ISSUE TITLE
"Edit chunk" gui problems

### ISSUE THREAD

**Issue by npo6ka** [Querz/mcaselector#138]
**Describe the bug**
I want to edit my chunk, but the "Edit chunk" gui are too small to do this

**To Reproduce**
1. Just click to "Edit Chunk"

**Screenshots and other files**
![img](https://sun9-7.userapi.com/c857424/v857424141/2366ac/RYvXHXM1ux8.jpg)

**Environment (please complete the following information):**
- OS: Windows 10
- Java version: 1.8.0_211
- Version 1.12.3

**Additional context**
- Minecraft 1.12
- Modpack PO3

**Comment by npo6ka** [comment]
![image](https://user-images.githubusercontent.com/13215491/90504858-5b1aa300-e15a-11ea-8d5c-de8ae8c5812d.png)

**Comment by Querz** [comment]
Can you please send me your `style.css`? There seems to be an error there.

**Comment by npo6ka** [comment]
style.css
https://pastebin.com/47Xp9G7E

**Comment by Querz** [comment]
Thanks. It appears that minifyCss was removing some semicolons in the css which should be ok, but for some reason the javafx CSSParser gets confused when a semicolon is missing at the end of a `url()`. I "fixed" this in the latest commit.

**Comment by npo6ka** [comment]
Thank you, it works!
