### ISSUE TITLE
1.16.1 support ?

### ISSUE THREAD

**Issue by Hellster90** [Querz/mcaselector#139]
Does this not work with 1.16.1 ?
I tried using it today but it won't work with my 1.16.1 world.
There's no error trying to open the world, but it just doesn't do anything

**Comment by Querz** [comment]
MCA Selector does support 1.16.1 worlds. If you would be so kind to tell me what exactly is not working, I can probably help you with that :)

**Comment by Hellster90** [comment]
I ran MCA Selector v1.10, then opened the DM-1 folder in it but it just sits there and doesn't do anything, doesn't seem to import the world in to the program, i even cleared all cache etc and tried v1.12.3 as well. It worked fine with my 1.16 world last time i tried 1.10, but just doesn't seem to be doing anything with 1.16.1 even with the newer version of MCA Selector.
I'm going to try rebooting my PC once i close everything and see if that makes any difference

**Comment by Querz** [comment]
Make sure to open the `region` folder in your `DIM-1` folder (the folder that contains `.mca` files).

**Comment by Hellster90** [comment]
Wow, i'm such an idiot, that worked, sorry
