### ISSUE TITLE
Method of using Java bundled with Minecraft for Windows doesn't work

### ISSUE THREAD

**Issue by bc-185** [Querz/mcaselector#144]
When I try to launch MCA Selector from the Windows PowerShell, it gives me this.

![mcaselector-powershell](https://user-images.githubusercontent.com/68671459/92510162-42813400-f1c0-11ea-852c-93e4ffa035a5.PNG)

However, I have found a way to work around this. :) The ZIP file below is an example of the workaround.

[mcaselector-1.12.3-additional-files.zip](https://github.com/Querz/mcaselector/files/5190014/mcaselector-1.12.3-additional-files.zip)

When the contents of this ZIP file are extracted to "C:\MCA-Selector" and the JAR file is placed there as well, clicking on the shortcut that says "MCA Selector", it launches MCA Selector.

**Comment by Querz** [comment]
Powershell recognizes everything before a space that is not surrounded by quotes as a command. So in your case, `C:\Program`, which is obviously not a command. If you escape a path to an executable that contains spaces with quotes, it also needs an `&` at the beginning so Powershell executes it.

The correct command in your case would be:
```
& "C:\Program Files (x86)\Minecraft\runtime\jre-x64\bin\java.exe" -jar "C:\MCA-Selector\mcaselector-1.12.3.jar"
```

**Comment by bc-185** [comment]
You didn't mention to type the additional characters in that command. I was so confused!

**Comment by Querz** [comment]
Ah sorry, I fixed the installation instructions now.

**Comment by bc-185** [comment]
Also, on windows, if you want to start it using a bat file will need to have this command (replace <path to mcaselector> with the path to the folder that hosts the jar file and <versionnumber> with the version number (like 13.1):

`"C:\Program Files (x86)\Minecraft\runtime\jre-x64\bin\java" -jar "<path to mcaselector>\mcaselector-<versionnumber>.jar`
