### ISSUE TITLE
Chunk finder by palette is broken on pre 1.13 format worlds?

### ISSUE THREAD

**Issue by Fixer-007** [Querz/mcaselector#146]
**Describe the bug**
Filter chunks - block palette does not work on pre format 1.13 worlds. For instance it happens in world from 1.8.8. Potential regression in https://github.com/Querz/mcaselector/commit/d8b68a9bace3ad3a44dbd1e1b4ef5bf0f7a63ef4 ? Last working version is 1.12.2

**To Reproduce**
1. Load 1.8.8 world with some torches/cobble/anyblock around
2. Tools - Filter Chunk - Find chunks containing said block
3. It does not find it at all

**Environment (please complete the following information):**
- OS: Windows 7
- Java version: 1.8.0_60
- Version: 1.13.1 (actually somewhere after 1.12.2)

**Comment by Querz** [comment]
Fixed in https://github.com/Querz/mcaselector/commit/9c60bb4b70cc4df97fc93e699fd7bf201341dd51 and will be in the next release.

**Comment by Querz** [comment]
Fix is in release [1.13.2](https://github.com/Querz/mcaselector/releases/tag/1.13.2).
