### ISSUE TITLE
Change Method of using Minecraft bundled Java to use Command Prompt instead of PowerShell?

### ISSUE THREAD

**Issue by bc-185** [Querz/mcaselector#147]
The Windows 8 method can be used with Windows 10, except that the path can be created by dragging the file, as Windows 10 has that feature. However, you would run the command in the Command Prompt. Also, this can be used with a batch file, while the PowerShell one must be used with a pp1 file, and running it requires right-clicking on the file. This means that you don't have to go through it every time.

A preview on what it would look like:

![mcaselectorsuggestion](https://user-images.githubusercontent.com/68671459/95115643-aa149b80-06fa-11eb-8dc6-7b39b1ea4514.PNG)

**Comment by Querz** [comment]
Release [1.14](https://github.com/Querz/mcaselector/releases/tag/1.14) now gives the option to download a Windows installer that downloads its own Java version to use exclusively with MCA Selector.

**Comment by bc-185** [comment]
> Release [1.14](https://github.com/Querz/mcaselector/releases/tag/1.14) now gives the option to download a Windows installer that downloads its own Java version to use exclusively with MCA Selector.

That is TRUE, but this was made long before that version.
