### ISSUE TITLE
It won't load JustenoughIDs worlds correctly

### ISSUE THREAD

**Issue by TurboSonic1** [Querz/mcaselector#148]
**Describe the bug**
When loading in a world that has JustenoughIDs it looks corrupted.

**To Reproduce**
1. Make a world with JustenoughIDs
2. Load the file
3. It shouldn't be read correctly and will cause this to happen as seen in the below screenshot

**Expected behavior**
It should be loaded in correctly

**Screenshots and other files**
![](https://cdn.discordapp.com/attachments/756301969605394434/763041550199423016/unknown.png)
[debug.log](https://github.com/Querz/mcaselector/files/5335285/debug.log)
[regionfile.zip](https://github.com/Querz/mcaselector/files/5335304/regionfile.zip)

**Environment (please complete the following information):**
- OS: Windows 10 64bit
- Java version: 1.8.0_261 64bit
- 1.12.2/1.14.4 with JustenoughIDs for map files

**Additional context**
As said before this is using a custom modpack and it got corrupted partially so we are trying to paste chunks in but it won't load the map files correctly.

**Comment by Querz** [comment]
MCA Selector currently does not support any mods that alter the block IDs, add new blocks or change the way chunks are saved. In contrary to what it says in the description of JEID, they do NOT use a palette like in vanilla 1.13, but rather an indexing to internal block IDs. Those block IDs can vary between different mod packs that use JEID, and different IDs may represent the same block so it is really difficult to create a block-color mapping (to render the map view) or use them in the filter, and impossible to do so without looking at the Minecraft installation with its mod packs.
