### ISSUE TITLE
Save the selection as a template?

### ISSUE THREAD

**Issue by ComputerJock** [Querz/mcaselector#149]
[Enhancement]

I'm about ready to update our 1.14 world to 1.16. I'd like to do it rather fine-grained in the overworld at least. An option to save my current selection as a template before I commit to the actual chunk deletion would be very, very useful. That would allow me to check the results and, if necessary, restore the backup and re-apply the template and apply corrections before deleting the chunks again.

**Comment by Querz** [comment]
You can export and import selections using `Selection-->Export selection` and `Selection-->Import selection` from the menu.

**Comment by ComputerJock** [comment]
I totally missed that. Thanks for the info. Sorry to bother you.
