### ISSUE TITLE
Issue finding a file

### ISSUE THREAD

**Issue by Bobby72000** [Querz/mcaselector#15]
I cannot seem to find the .mca that mcaselector is supposed to look at in order to do anything. I use Twitch in order to play minecraft.

**Comment by Querz** [comment]
I don't know where the Twitch launcher stores the Minecraft files as i've never used it. The MCA Selector opens the default save folder of the Minecraft launcher from Mojang.
Maybe [this Reddit post](https://www.reddit.com/r/projectozone2/comments/68w6zz/where_does_the_twitch_client_keep_its_minecraft/) might help you out?

**Comment by Bobby72000** [comment]
The Twitch Launcher usually keeps its Minecraft files in the Install folder in the Twitch or Curse Folder (If you upgraded to Twitch from Curse).
Ex. C:\Users\USER\Twitch\Minecraft\Install

**Comment by Querz** [comment]
They should be in `<minecraft installation folder>/saves/<world name>/region`

**Comment by Bobby72000** [comment]
What's special, is that the saves are actually contained in the modpack files. As to not let you play a save which is on the moon (by using Galacticraft), on a pack which doesn't contain Galacticraft. I'll be confirming if the .mca's are in the region files.

**Comment by Bobby72000** [comment]
They are indeed in there, and not in some weird place where they aren't supposed to be in.
I'll be closing this due to the fact that the issue i have been having has been solved.
