### ISSUE TITLE
[Feature Request] Add 1.16.x support

### ISSUE THREAD

**Issue by Dawoox** [Querz/mcaselector#150]
Can you add support for version 1.16.x?
For these versions very little software exists to make this type of modification, McEdit is no longer compatible with these new versions.
I don't know if it's possible to do that, but it would help a lot a large part of the community!

NB: With the current version of the software if you load a world 1.16.x nothing is displayed.

**Comment by Querz** [comment]
MCA Selector does support 1.16.x worlds. Make sure to open the `region` folder of either your overworld, nether or end :)

**Comment by Dawoox** [comment]
Sorry for the mistake, so I close the issue.
