### ISSUE TITLE
Selection radius option in Filter chunks messes up selections for whole regions

### ISSUE THREAD

**Issue by Fixer-007** [Querz/mcaselector#152]
**Describe the bug**
If you set "selection radius" to some number (say 3) in Filter chunks, during scan for inhabited time >1 days (as example) it works ok at first but after processing neighboring (?) parts selection gets messed up with empty center and thing selected part of some regions.
Here is example from mindcrack S4 world. Filter settings:
![Filter chunks](https://user-images.githubusercontent.com/16494741/97617517-89541300-1a26-11eb-855b-c89ffb6b576f.png)
![sel0](https://user-images.githubusercontent.com/16494741/97617300-42feb400-1a26-11eb-90a5-ae84ff842fc9.png)
if i set "selection radius" to 1,2,3-whatever I got those weird deselected parts in center:
![sel3](https://user-images.githubusercontent.com/16494741/97617368-57db4780-1a26-11eb-9961-31244fd7e745.png)

**Environment (please complete the following information):**
- OS: Windows 7
- Java version: 1.8.0_261
- Version: 1.13.2

**Comment by Querz** [comment]
Fixed in [1.13.3](https://github.com/Querz/mcaselector/releases/tag/1.13.3).
