### ISSUE TITLE
Releases Page says "MaxOS" instead of MacOS at the botton

### ISSUE THREAD

**Issue by AwesomeKalin** [Querz/mcaselector#154]
**Describe the bug**
At the bottom, where it says, "To avoid having to go through this process every time to start MCA Selector, the resulting command can be copied into a .bat-file on Windows or .sh-file on MaxOS and Linux and can then be executed by double-clicking the .bat-file on Windows or running sh <file>.sh in the terminal / console on MacOS or Linux where <file> must be replaced by the name of the .sh-file." It says MaxOS in one place instead of MacOS.

**To Reproduce**
N/A

**Expected behavior**
It should say MacOS

**Screenshots and other files**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Querz** [comment]
Fixed :)
