### ISSUE TITLE
Help with MCA Selector : Where is the height ?

### ISSUE THREAD

**Issue by Zephyr2090** [Querz/mcaselector#156]
Hi,

I would like to transfer one of my world to another one, but there is an height issue.

The world I want to transfer is at 17 of z-pos, and the rest of my new world is at 63 in z-pos.

Can someone help me? Maybe I'm blind... ?

Thanks.

![2020-12-01_00 51 14](https://user-images.githubusercontent.com/75284113/100680650-4c0ada00-3372-11eb-8b58-9a6ee2bf7b70.png)

**Comment by Querz** [comment]
You can currently not move chunk sections vertically.

**Comment by Zephyr2090** [comment]
> You can currently not move chunk sections vertically.

Hello!
Thanks for your reply.

Do you have some workaround to correct that? Because it's quite annoying ^^'

**Comment by narcarsiss** [comment]
@Zephyr2090 The only way to fix this would be to use FAWE or Worldedit, Copy a few layers under your World to the height you want.  
Save it as a Schematic  
Then load that schematic back into the new world.  
  
Checkout Tutorials on Worldedit or FAWE :)
