### ISSUE TITLE
[Suggestion] option to select filtered chunks only within previous selection

### ISSUE THREAD

**Issue by nofabe** [Querz/mcaselector#161]
this would be really handy if you don't want to search the whole map but only a specific area, without having to manually add xPos and zPos restriction having to look up the coordinates of the area you want to search, especially if it's a more complex shape than a square - Export and Delete already have that option (if it does what I assume it does), so Select should, too

**Comment by Querz** [comment]
Fixed in release [1.14](https://github.com/Querz/mcaselector/releases/tag/1.14).
