### ISSUE TITLE
[Suggestion] Multi Threading 

### ISSUE THREAD

**Issue by Polarbub** [Querz/mcaselector#162]
I have no idea how to implement this but could you make it use multiple cores? I'm filtering 30GB worlds and it takes a while only using ~12% of my 8 core 16 thread cpu. I also had to increase the stack otherwise it would hang.

**Comment by Querz** [comment]
The amount of threads it uses for loading / processing and saving data can be adjusted in `File-->Settings`.

I recommend setting `Read Threads` to 1 (This is very fast and bottlenecked by processing anyway), `Process Threads` to the amount of threads your CPU but not more than that, and `Write Threads` to 4 (most of the time this is also bottlenecked by processing, so more threads don't really improve anything).
`Max Loaded Files` regulates how many files are loaded and processed at the same time, you can play around with this setting while also changing the `-Xmx` for your JVM.
