### ISSUE TITLE
[Suggestion] An option in settings for default directory 

### ISSUE THREAD

**Issue by DereC4** [Querz/mcaselector#163]
I know most people have their worlds in the saves folder but I have multiple profiles which are linked to different folders in order to not conflict and for easier launching, and I was wondering if an option could be added to change the default directory for world saves (when searching for a file or using ctrl+o)

An example would be 
C:\Users\(name)\AppData\Roaming\.minecraft\saves

**Comment by Querz** [comment]
Added in release [1.14](https://github.com/Querz/mcaselector/releases/tag/1.14).

**Comment by DereC4** [comment]
Thanks!
