### ISSUE TITLE
Execution failed for task ':compileJava'.

### ISSUE THREAD

**Issue by asdfghjkl403622** [Querz/mcaselector#166]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

above is the error, here is the full output: https://pastebin.com/9SS24QKi 

done with default jdk for Ubuntu 20.10.

**Comment by Querz** [comment]
It looks like your Java installation is missing JavaFX. Please refer to https://github.com/Querz/mcaselector/issues/6 for options regarding this issue.

**Comment by amanzversal** [comment]
any solution of the above issue
