### ISSUE TITLE
[Feature Request / Help] Partially reset chunks to keep builds when converting to 1.17

### ISSUE THREAD

**Issue by stanaron** [Querz/mcaselector#167]
Hi there,

I saw a similar topic discussed here: https://github.com/Querz/mcaselector/issues/114
But I didn't fully understand what the solution would be.

I'm wondering if / how it would be possible to keep my builds on the surface (or down to a certain altitude) but reset the chunks below a certain altitude to get the new caves and extra depth of 1.17 when it comes out?

**Comment by Querz** [comment]
[Here](https://gist.github.com/Querz/008111195cc7bc012bb291849d2eb9c7#partially-importing-chunks) are instructions of how to do this with the nether, but they apply to the overworld as well.
I don't know yet how Mojang plans to change terrain generation above y=64 though, so this might not look completely seamless.
