### ISSUE TITLE
MCC oversized chunk handling

### ISSUE THREAD

**Issue by Storm-Cloud** [Querz/mcaselector#169]
A feature of minecraft 1.15+ is that if a chunk becomes larger than the 4096 byte limit, it will be moved to a seperate file titled c.x.z.mcc (x and z being the chunk coordinates) and saved next to the mca files. The mca header for that chunk will be changed to 00 00 00 01 82, the 8 referring to the fact that the chunk is now stored separately, everything that would normally follow is then placed into the mcc file.

At present the program handles assumes these oversized chunks are empty, or fails to load them.

**Comment by Querz** [comment]
Quote:

> The uncompressed data is in NBT format and follows the information detailed on the chunk format article; if compressed with compression scheme 1, the compressed data would be the same as the on-disk content of an Alpha chunk file. Note that chunks are always saved using compression scheme 2 by the official client.
> 
> If the value of compression scheme increases by 128, the compressed data is saved in a file called c.x.z.mcc, where x and z are the chunk's coordinates, instead of the usual position.

From [the Minecraft Wiki](https://minecraft.gamepedia.com/Region_file_format)

**Comment by Querz** [comment]
Fixed in release [1.14](https://github.com/Querz/mcaselector/releases/tag/1.14).
