### ISSUE TITLE
[Suggestion]Allow filter to find dense amounts of redstone type blocks.

### ISSUE THREAD

**Issue by Error438** [Querz/mcaselector#170]
Allow filter to find dense amounts of redstone type blocks so it is easy to find lag machines on server worlds.

**Comment by Querz** [comment]
This is a bit vague... There are so many scenarios where this would not work as intended:
- Lag machines that do not use redstone (e.g. just stacking entities)
- When the redstone is not densely packed, but still generating lag
- What is "densely packed"? If someone builds one of those big piston doors from YouTube, isn't that also "densely packed" redstone?

A possible option would be to add a filter that lets you search for a specific block / entity *and* how often it appears in a chunk, so if there's e.g. a lag machine using wooden doors you could just search for all chunks that contain a specific threshold of wooden doors.

**Comment by a8underscore** [comment]
maybe just to filter chunks with redstone in them?

**Comment by Querz** [comment]
I think this is covered with the new [overlays](https://github.com/Querz/mcaselector#overlays). There is one to look for entities in a chunk and one to count block types.
