### ISSUE TITLE
JavaFX

### ISSUE THREAD

**Issue by ZeburaBlack** [Querz/mcaselector#171]
![image](https://user-images.githubusercontent.com/56888661/109257467-3c126300-77c6-11eb-856b-e5f898220b2e.png)

cant seem to get it to work, all attempts of using the powershell methods result in errors, such as "unrecognized option --module-path"

java version is:
1.8.0_281

**Comment by Querz** [comment]
It looks like your `java` command is linked to Java 8, but it leads you to Java 15 when you try to open the file directly.
Try to run the Java command without the `--module-path` and `--add-modules` options.

Or if you don't care about Java, there now is a Windows installer that does everything for you with the new [1.14](https://github.com/Querz/mcaselector/releases/tag/1.14) release.

**Comment by t-richards** [comment]
For what it's worth, I'm experiencing the same problem running the `.jar` on Linux with only OpenJDK 15 and OpenJFX 15 installed.

It works when I drop back to Java 8.

**Comment by oskarkk** [comment]
I had the same problem, turned out that in the Arch repository the newest version of JavaFX is 15.0.1: https://archlinux.org/packages/extra/x86_64/java-openjfx/

I tried it on Java 11 with:

```
#!/bin/sh

export PATH="/usr/lib/jvm/java-11-openjdk/bin/:$PATH"
exec java --module-path /usr/lib/jvm/java-11-openjfx/lib --add-modules ALL-MODULE-PATH -jar ~/software/mcaselector.jar
```

and it worked, but I've encountered a bug with overlays: #185 

So I'd recommend Java 8.

**Comment by Querz** [comment]
I assume this has been solved:
* Make sure that the version of the `java` *command* is 1.8.x
* If it is *not* 1.8.x, use the instructions provided in the README to get and run it with JavaFX
* If it *is* 1.8.x, make sure that you have JavaFX installed.
* Or use a JRE that already contains JavaFX like the Oracle JRE 8 or one of the [Azul Zulu JRE FX builds](https://www.azul.com/downloads/?version=java-8-lts&package=jre-fx).
