### ISSUE TITLE
Export selected chunks stopped working in 1.14+

### ISSUE THREAD

**Issue by AronParker** [Querz/mcaselector#174]
**Describe the bug**
Export selected chunks stopped working.

**To Reproduce**
1. Go to 'Selection'
2. Click on 'Export selected chunks'
3. Wrong dialog text: "You are about to delete xx chunks"
4. output folder contains 3 empty folders: entities, poi and region

**Expected behavior**
The exported region files (e.g. r.-2.-1.mca)

**Environment (please complete the following information):**
- OS: Windows 10
- Java version: openjdk 15.0.2 2021-01-19
- Version 1.14 - 1.14.1

**Comment by Querz** [comment]
Thanks, fixed int [1.14.2](https://github.com/Querz/mcaselector/releases/tag/1.14.2)
