### ISSUE TITLE
Drag & Drop world folders to open them

### ISSUE THREAD

**Issue by michuXYZ** [Querz/mcaselector#175]
The interface is clean, simple, but helpful, it supports many languages, easy to use, in options you can customize everything including threads that are used etc., everything nice, but i miss here one thing, i know that its incredibly hard to do... and impossible... but... ADD DRAG AND DROPPING it would be nice haha

**Comment by Querz** [comment]
Thanks
What would you like to drag and drop?

**Comment by TheRealBeaver** [comment]
@Querz probably being able to drag & drop worlds into the program

**Comment by Querz** [comment]
Sure, that would work

**Comment by Querz** [comment]
Added in release [1.15.1](https://github.com/Querz/mcaselector/releases/tag/1.15.1).
