### ISSUE TITLE
JavaFX

### ISSUE THREAD

**Issue by 1schlick** [Querz/mcaselector#179]
So I've installed javaFX from this website https://gluonhq.com/products/javafx/ and it appears to just be a folder with a bunch of files in it... Is there anything else I'm supposed to do to make this work?

<img width="584" alt="Screen Shot 2021-03-14 at 3 24 24 PM" src="https://user-images.githubusercontent.com/53189655/111086439-5c863100-84d9-11eb-9f11-b9f39aee3f47.png">

<img width="246" alt="Screen Shot 2021-03-14 at 3 23 32 PM" src="https://user-images.githubusercontent.com/53189655/111086429-51cb9c00-84d9-11eb-8c96-39200c174d12.png">

**Comment by Querz** [comment]
You are using the JavaFX SDK 16, but you have Java 15.0.1 installed. Older versions are not directly linked on that site, so you can either get Java 16 or build the link yourself for 15.0.1: https://gluonhq.com/download/javafx-15-0-1-sdk-mac
