### ISSUE TITLE
Question - Can this edit chunks?

### ISSUE THREAD

**Issue by Cobwebster** [Querz/mcaselector#18]
Can this do things like the old mcedit? Could I purge a chunk and make it so its just empty space instead of regenerating when loading? aka not deleting the chunk file but editing the blocks selected.

**Comment by Querz** [comment]
The purpose of this tool is to delete, export and import chunks. You can edit values on the chunk level like the chunk status, inhabited time or the biome, but not change anything on block level.

**Comment by Cobwebster** [comment]
> The purpose of this tool is to delete, export and import chunks. You can edit values on the chunk level like the chunk status, inhabited time or the biome, but not change anything on block level.

Ah okay, I think I was linked the wrong thing for what I was looking for by someone :P is MCedit still the standard when it comes to region block editing or is there a better thing now.

**Comment by Querz** [comment]
Unfortunately my knowledge of MCEdit is very limited and i don't really follow its development.
I found this [Reddit post](https://www.reddit.com/r/Minecraft/comments/b2tt9u/mcedit_alternative/eiwuy9j/) that states that MCEdit was "dead" but the developers are working on something called "Amulet" (see https://www.amulet-editor.com/).
