### ISSUE TITLE
Waterlogged top slabs show up as water blocks

### ISSUE THREAD

**Issue by xiej2520** [Querz/mcaselector#181]
**Describe the bug**
Waterlogged top slabs show up as blue water blocks in MCA Selector.

**To Reproduce**
1. Place top slabs and water log them
2. Load the world in mcaselector
3. Blocks show up as blue

**Expected behavior**
MCA Selector generally displays the top block, so the slab should be shown.

**Screenshots and other files**
![2021-03-22 (1)](https://user-images.githubusercontent.com/16630834/112081229-b205b200-8b59-11eb-868b-e6945a86a2d7.png)
![Capture](https://user-images.githubusercontent.com/16630834/112188877-cbe6d980-8bd9-11eb-8cec-60c55fc4e98a.PNG)

**Environment (please complete the following information):**
- OS: Windows 10
- Java version: 1.8.0_261
- Version 1.14.2

**Additional context**
Minecraft 1.16.5, 1.14.4 both displayed the same.

**Comment by Querz** [comment]
Fixed in [release 1.15](https://github.com/Querz/mcaselector/releases/tag/1.15)
