### ISSUE TITLE
[Feature Request] Copy subchunks

### ISSUE THREAD

**Issue by pixelplanetdev** [Querz/mcaselector#182]
With 1.17 on the horizon i just want to drop the suggestion to be able to copy vertical subchunks or even parts of chunks between given y-levels.
This would make it possible to regenerate just the lower underground stuff by generating a fresh world with the same seed in 1.17, generating all necessary chunks, and then copying the bottom subchunks over.

**Comment by Querz** [comment]
This is already possible since Minecraft 1.16. [Here](https://gist.github.com/Querz/008111195cc7bc012bb291849d2eb9c7) is a tutorial on how you can merge 2 worlds vertically, which will also apply to 1.17.

**Comment by pixelplanetdev** [comment]
oh, amazing, didn't know that. Thanks a lot.
