### ISSUE TITLE
"The application was configured to use a bundled Java Runtime Environment but the runtime is missing or corrupted."

### ISSUE THREAD

**Issue by FireFall-YT** [Querz/mcaselector#184]
![image](https://user-images.githubusercontent.com/58619409/113156882-1227e280-9243-11eb-86a7-a855427663e7.png)

**Comment by Querz** [comment]
I can't reproduce this. Was there an error during installation? Are you using the installer from the most recent release (1.15)?
Just try to reinstall it and see if that worked.

**Comment by FireFall-YT** [comment]
I install version 1.15, and when i open MCASelector, i see this message.

**Comment by Querz** [comment]
Can you go into the installation folder and show me what files are inside?

**Comment by bc-185** [comment]
For now, you can install Java and open the file `mcaselector.jar` inside of the install directory. If you have Java, but it won't open, you can try this command: 
`java -jar mcaselector.jar`

You can put this command inside of a batch file inside of the directory if you want to.
If there is a directory named `jre` inside, make sure that there is `javaw.exe` inside the `bin` folder.

Java Download:
https://java.com/download

**Comment by bc-185** [comment]
This error is actually caused because the installer fails to rename `zulu8.52.0.23-ca-fx-jre8.0.282-win_x64` to `jre` under certain conditons. Rename `zulu8.52.0.23-ca-fx-jre8.0.282-win_x64` to `jre` if this happened.
