### ISSUE TITLE
FTB Chunks compatibility

### ISSUE THREAD

**Issue by Yucareux** [Querz/mcaselector#186]
Hi, i was wondering if its possible for MCA Selector to be compatible with ftb chunks, so chunks that are claimed by players can be selected, then invert the selection, and delete all the chunks that are not claimed. (as an use example)

**Comment by Querz** [comment]
Can you send me one of the .mca-files that would be affected? Or is there a documentation how this data is stored?

**Comment by Yucareux** [comment]
> Can you send me one of the .mca-files that would be affected? Or is there a documentation how this data is stored?

So, the files related to chunks claimed are on world/data/ftbchunks, and are json files, like this one.

[b168bc122f3f306989507c8929a552bb-Yucareux.zip](https://github.com/Querz/mcaselector/files/6270129/b168bc122f3f306989507c8929a552bb-Yucareux.zip)

**Comment by Yucareux** [comment]
Here is another example

[be4d6cd1c34034c18eaa51bfb04c9363-MashiMaro1924.zip](https://github.com/Querz/mcaselector/files/6270187/be4d6cd1c34034c18eaa51bfb04c9363-MashiMaro1924.zip)

**Comment by Querz** [comment]
Selections can be imported as .csv files. Their format works like this:
```csv
[inverted]
<region-x>;<region-z>[;<chunk-x>;chunk-z]
<region-x>;<region-z>[;<chunk-x>;chunk-z]
...
```
Converting your first example json file to this format, it looks like this:
```csv
-2;0;-36;0
-2;0;-36;1
-2;-1;-36;-1
-2;-1;-34;-1
-2;0;-34;0
-2;0;-34;1
-2;0;-35;1
-2;-1;-35;-1
-2;0;-35;0
-1;-1;-32;-1
-1;0;-32;0
-1;0;-32;1
-2;0;-33;0
-2;0;-33;1
13;-7;422;-197
13;-7;422;-196
13;-7;422;-195
13;-7;422;-194
-1;-1;-31;-1
-1;0;-31;0
13;-7;423;-197
13;-7;423;-196
13;-7;423;-195
13;-7;423;-194
```
You then can simply write a simple script to convert the FTP Chunks format to this csv format and import that file through `Selection --> Import selection`, then invert the selection and delete the selected chunks.

I wrote a simple program that can do this, just run it like this:
```
java -jar ftbchunks2mcaselector.jar /path/to/directory/with/json/files/ minecraft:overworld
```
This should extract all chunk claims from those json files and create an `output.csv` file that can be imported into MCA Selector.

[ftbchunks2mcaselector.jar.zip](https://github.com/Querz/mcaselector/files/6271844/ftbchunks2mcaselector.jar.zip)

[Source here](https://github.com/Querz/FTBChunks2MCASelector)

**Comment by Yucareux** [comment]
C:\Users\tomyt\Desktop>java -jar ftbchunks2mcaselector.jar C:\Users\tomyt\Downloads\ftbchunks.3zTp\ftbchunks\world\data\ftbchunks minecraft:overworld
Exception in thread "main" org.json.JSONException: JSONObject["minecraft:overworld"] not found.
        at org.json.JSONObject.get(JSONObject.java:572)
        at org.json.JSONObject.getJSONArray(JSONObject.java:765)
        at net.querz.ftbchunks2mcaselector.Main.main(Main.java:37)

**Comment by Yucareux** [comment]
Got that issue

**Comment by Querz** [comment]
[ftbchunks2mcaselector.jar.zip](https://github.com/Querz/mcaselector/files/6272724/ftbchunks2mcaselector.jar.zip)
Added some more debugs and made it not crash when it can't read something.

**Comment by Yucareux** [comment]
got it working now, thank you :)
