### ISSUE TITLE
Chunks can no longer be deleted in 1.15.2

### ISSUE THREAD

**Issue by adammglover** [Querz/mcaselector#191]
**Describe the bug**
Chunks aren't deleted in version 1.15.2 of MCASelector. You can select chunks and attempt to delete them but nothing ends up happening. 

**To Reproduce**
Load up a 1.16.5 map and try and delete a chunk, or a selection of chunks.

**Expected behavior**
The chunks should be deleted.

**Environment:**
- OS: Windows 10
- Java version: 8.0.2410.7
- Version 1.15.2

**Additional context**
* Worlds were generated on 1.16.4/1.16.5.
* They're vanilla maps.
* Version 1.15.1 of MCASelector successfully deletes the chunks.
* Entire regions are still able to be deleted successfully.

**Comment by Querz** [comment]
Fixed in [release 1.15.3](https://github.com/Querz/mcaselector/releases/tag/1.15.3).
