### ISSUE TITLE
Place chunck before import

### ISSUE THREAD

**Issue by Synt3x** [Querz/mcaselector#20]
Hello Querz, great work with this tool.

I was wondering if it's possible to add the feature to place the chunks you are importing, instead of overwriting the existing world (.mca). Because I'm currently manually renaming the .mca until it's in a chunk I want.

edit:
I was to quick to type, when entering a chunk that I manually moved the server crashed.
But it would be great if it was possible to select where to place the new chunks.

**Comment by Querz** [comment]
That's a good point.
I could simply add a UI element to the confirmation dialog (The dialog that asks you whether you want to override existing chunks or not) that accepts an offset in chunk coordinates, similar to the GoTo dialog.

**Comment by GiftCarder-API** [comment]
I'd be very interested in this. Any news?

**Comment by LaryIsland** [comment]
I would also really appreciate this being implemented.

**Comment by Querz** [comment]
You can have a look at #24 And test it if you want. Sorry for the long waiting time, it was more complex than it looks like (concurrency, merging multiple files into a single file).
There is also a download for a compiled version if you don't want to build it yourself.

I currently don't have access to Minecraft, so it would be nice if someone could test opening a world with imported chunks (with an offset) in Minecraft.

**Comment by Querz** [comment]
Published in release [1.7.4](https://github.com/Querz/mcaselector/releases/tag/1.7.4).
