### ISSUE TITLE
How do I open a world?

### ISSUE THREAD

**Issue by Keheck** [Querz/mcaselector#21]
I have no idea how to open a world...

**Comment by Querz** [comment]
It would be nice if you could provide some more information:
* What OS are you playing on?
* What Minecraft version are you playing?
* What have you tried yet?
* Are there any error messages?
* Anything else that might be important?

Thanks! :)

**Comment by Keheck** [comment]
Os: Windows 7
MC version: 1.14.2
Things I've tried:
* Open as a zip (does'nt show up)
* Selecting the world wolder itself
* Opening level.dat (doesn't show up)

No error messages

**Comment by Querz** [comment]
You need to navigate to the `region` folder inside your world folder which contains files like `r.0.0.mca`.
