### ISSUE TITLE
Error: JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by AeroInf** [Querz/mcaselector#214]
![Capture](https://user-images.githubusercontent.com/85600991/121296441-e9a90e00-c8ad-11eb-9aba-8440f9c2aed4.JPG)
Yeah, this comes up after i click the latest version of MCA selector

**Comment by UZEEK** [comment]
Same WIth Me Too!

**Comment by Querz** [comment]
Since release 1.16, MCA Selector requires Java 16 to run. For Windows, I recommend using the Windows installer which will handle the Java installations automatically; Fpr MacOS and Linux there are installation instructions in the Readme [here](https://github.com/Querz/mcaselector#using-a-jre-or-jdk-with-pre-packed-javafx-the-simple-way).

**Comment by UZEEK** [comment]
how to please...i don't understand

**Comment by UZEEK** [comment]
> Since release 1.16, MCA Selector requires Java 16 to run. For Windows, I recommend using the Windows installer which will handle the Java installations automatically; Fpr MacOS and Linux there are installation instructions in the Readme [here](https://github.com/Querz/mcaselector#using-a-jre-or-jdk-with-pre-packed-javafx-the-simple-way).

Please how to do it..i can't help pls

**Comment by Querz** [comment]
@UZEEK You download the installer for Windows and run it. Every release has a `MCA_Selector_Setup.exe` file that you can download, or you download the most recent "Windows installer" version from [here](https://github.com/Querz/mcaselector#download-and-installation) (which is just a direct download link to that file). If you are on MacOS or Linux, download the "Universal" version from the same page and follow the [instructions](https://github.com/Querz/mcaselector#using-a-jre-or-jdk-with-pre-packed-javafx-the-simple-way).
