### ISSUE TITLE
Error: Please install Java Fx

### ISSUE THREAD

**Issue by AeroInf** [Querz/mcaselector#216]
After downloading Java16 I was prompted to this message 
![Capture](https://user-images.githubusercontent.com/85600991/121454536-364d2180-c960-11eb-925c-37e035c9c0b8.JPG)

**Comment by NJR1202** [comment]
I have the exact same problem.

**Comment by emnbdx** [comment]
All needed informations at end of readme ;
https://github.com/Querz/mcaselector#download-and-installation

**Comment by Querz** [comment]
For Windows, you can use the Windows installer that will automatically install everything for you. The Windows installer can be downloaded alongside the universal jar file [at the bottom of each release](https://github.com/Querz/mcaselector/releases/tag/latest).
If you would like to run the universal jar instead, there are instructions on how to proceed when this error message pops up [here](https://github.com/Querz/mcaselector#when-you-receive-an-error-from-a-previously-installed-version-of-java).
