### ISSUE TITLE
Won't launch on Mac OS

### ISSUE THREAD

**Issue by iep1000** [Querz/mcaselector#217]
I tried to open the latest version, 1.16.2, and it gives a window that says "The Java Jar file "mca-selector-1.16.2.ar" could not be launched. Check the Console for possible error messages." 

I can still open 1.15.4, which is the previous version I had downloaded, and it still works perfectly fine.

**Comment by rhettl** [comment]
seconded. 

Big Sur 11.2.1
MacBook Pro 15" 2017

**Comment by Querz** [comment]
Since release 1.16 MCA Selector needs Java 16 to launch. Please refer to the [installation instructions](https://github.com/Querz/mcaselector#using-a-jre-or-jdk-with-pre-packed-javafx-the-simple-way) for further information.
