### ISSUE TITLE
A java Exception has occurred |&| Error: JNI error has occurred, please check your installation and try again | I cant fix it Please help

### ISSUE THREAD

**Issue by UZEEK** [Querz/mcaselector#220]
<img width="304" alt="Screenshot 2021-06-11 184439" src="https://user-images.githubusercontent.com/85610521/121692012-42aeb700-cae5-11eb-86e0-65baad64b9a5.png">
<img width="187" alt="Screenshot 2021-06-11 184507" src="https://user-images.githubusercontent.com/85610521/121692018-44787a80-cae5-11eb-8295-e0c78140269f.png">

I CAN'T SEEM TO FIX IT.
I DON'T KNOW HOW TO PLEASE GUIDE ME THROUGH IT...PLEASE
*SORRY FOR THE CAPS...MY CAPS IS NOT WORKING

**Comment by Querz** [comment]
For Windows, you can use the Windows installer that will automatically take care of the Java installation: https://github.com/Querz/mcaselector/releases/download/1.16.2/MCA_Selector_Setup.exe
