### ISSUE TITLE
Question regarding generating a world image

### ISSUE THREAD

**Issue by viral32111** [Querz/mcaselector#221]
Hey, I'm trying to use this tool to generate a top-down image of the *entire explored* world.

***

So far I've used the following commands:
```sh
# Get all used chunks
java -jar mcaselector.jar --mode select --region 'world\region' --query 'InhabitedTime > 0' --output 'used-chunks.csv'

# Render an image
java -jar mcaselector.jar --mode image --region 'world\region' --selection 'used-chunks.csv' --output 'world.png'
```

However, the issue with those is that the final image sometimes contains missing chunks in the middle of existing chunks (see the areas in the red boxes), due to using the `InhabitedTime > 0` filter and since no players have ever entered those chunks.

![MissingChunks](https://user-images.githubusercontent.com/19510403/121697890-06676080-cabd-11eb-9a7d-89d107f9f8ee.png)

***

I then tried using the `Status` filter to select all chunks that have been generated *(at least I think that's what this filter is for?)*:
```sh
# Get all generated chunks
java -jar mcaselector.jar --mode select --region 'world\region' --query 'Status = full' --output 'generated-chunks.csv'

# Render an image
java -jar mcaselector.jar --mode image --region 'world\region' --selection 'generated-chunks.csv' --output 'world.png'
```

However, this fails with the error message `dimensions are too large to generate an image: 16563760x22243472`, because I'm guessing the filter is selecting way too many chunks in the world, instead of just the generated ones?

***

**Is there a query/filter I can use that will *only* select the chunks that have been generated in the world so I can export an image of the entire explored world?**

**Comment by Querz** [comment]
It depends on how big your world is. The maximum image size is currently limited to not have more than 2,147,483,647 pixels (2 GigaPixels (!)). If you want a square image, you can have a maximum width and height of 46340 pixels.

The limit is there for technical reasons, but could theoretically be expanded (saving the image as png will take forever though). On top of that you would need to find a program that is capable of loading a png image of that size (streaming?).

I suggest you adjust your second filter to limit the size as well using the `xPos` and `zPos` filters, something like this:
```
xPos < 1448 AND xPos > -1448 AND zPos < 1448 AND xPos > -1448
```

**Comment by viral32111** [comment]
Yeah I thought about using the `xPos` and `zPos` thing, and did try it, but that only goes out from the centre of the world and it's possible that a player could've gone through the Nether for quite a while then emerged in the overworld far outside of that central radius, thus generating chunks that have no direct generated path to the centre of the world. Then again, I'm not 100% sure on the maximum explored size of my world right now so maybe it will be okay.

I'll try it in a few days as right now I'm busy, so I'm gonna leave the issue open if that's alright, just incase I have any additional questions when it comes to it. I'll also look into that cache images one, didn't think about that. Thank you!

**Comment by viral32111** [comment]
Okay, I managed to get it done so I'm gonna close this now. Got no extra questions and it all went fine, the `xPos` and `zPos` worked pretty well but I had to use the GUI to add a few more regions/chunks to the selection that were outside it.
