### ISSUE TITLE
Mobs (Wolfs, Horses) not transferring over from world to world.

### ISSUE THREAD

**Issue by kavoo0** [Querz/mcaselector#222]
So mobs will not transfer from a 1.16 world to my 1.17 world for me.

If I copy a chunk with the entity in it, and paste it to a new chunk, it will not transfer.

Edit: Back when 1.16.5 was the latest version of Minecraft, it seemed to work fine.

**Comment by Querz** [comment]
Specifically, this bug affects copying *all* entities from a 1.17 world into another world. Copying from any source that is 1.16.5 or below works fine.

**Comment by kavoo0** [comment]
Only when I transfer chunks from a 1.16.5 world to a new 1.17 world. 
I believe it has something to do with the new entities folder

![image](https://user-images.githubusercontent.com/85761156/122479962-f6a6bb00-cf99-11eb-8bd7-f1c6914604be.png)

**Comment by Querz** [comment]
Fixed in [release 1.16.3](https://github.com/Querz/mcaselector/releases/tag/1.16.3).
