### ISSUE TITLE
Bug: Applying a change in the edit chunk window results in an error message.

### ISSUE THREAD

**Issue by Zitchas** [Querz/mcaselector#224]
**Describe the bug**

**To Reproduce**
1. Select a chunk
2. Click on 'edit chunk'
3. Make a change to the chunk, such as changing the Status to something else.
4. Click apply.
5. See error.

Note: upon closing and reopening MCA selector and going back to the same chunk, it appears that it did actually save the change.

**Expected behavior**
The change gets applied to the chunk and the dialog box closes.

**Screenshots and other files**
The results from the "Copy to clipboard" option:
java.lang.NullPointerException: Cannot invoke "net.querz.mcaselector.io.mca.Chunk.getTimestamp()" because "chunk" is null
	at net.querz.mcaselector.io.mca.MCAFile.saveSingleChunk(MCAFile.java:351)
	at net.querz.mcaselector.ui.dialog.NBTEditorDialog.writeSingleChunk(NBTEditorDialog.java:275)
	at net.querz.mcaselector.ui.dialog.NBTEditorDialog.lambda$new$1(NBTEditorDialog.java:76)
	at net.querz.mcaselector.ui.dialog.ProgressDialog$1.call(ProgressDialog.java:59)
	at net.querz.mcaselector.ui.dialog.ProgressDialog$1.call(ProgressDialog.java:56)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Environment (please complete the following information):**
- OS: Windows 10
- Java version: Java 1.8u21 & OpenJDK 16.0.1_9
- Version 1.16.2

**Additional context**
Add any other context about the problem here, e.g.:
- Minecraft version used to generate affected parts of your world: Originally generated in 1.8, most recently played in 1.16.5
- Mods used that change Minecraft save files or add blocks to the game: No mods, plugins, or datapacks in use.
- Previously used programs to alter the world files: None.

**Comment by Querz** [comment]
It fails to save the `poi` file in this case, because the chunk data is empty. The `region` data is still saved. This is indeed a bug and will be fixed in the next release.

**Comment by Zitchas** [comment]
OK. Thanks.

As a bit of a follow up, if I use "open region" instead of "open world" the map looks the same, but I can now edit the chunk without it giving errors. Unfortunately, when I edit it a second time, the value has reset to the original value.

**Comment by Querz** [comment]
Make sure to press `Enter` to finish editing a value before using `Apply` to save the changes.

**Comment by Zitchas** [comment]
OK, will remember to do that.

**Comment by Zitchas** [comment]
I tried doing that, but I still get error messages, and the value I enter into the "status" field isn't saved. Actually, it seems to be saved temporarily - If I open up the edit chunk box, the value will indeed be saved; but if I go edit a few more chunks then go back to check it, then the value has reset to its original value.

**Comment by Querz** [comment]
Fixed in [release 1.16.3](https://github.com/Querz/mcaselector/releases/tag/1.16.3).
