### ISSUE TITLE
Having trouble installing on MacOS

### ISSUE THREAD

**Issue by iep1000** [Querz/mcaselector#225]
I'm on MacOS and I've been having trouble installing the version 1.16.2. I've downloaded and installed Java SE 1.16 and the zulu zip file. But when I try to drag it and mcaselector into terminal but it says "no such user or named directory: jar". Did I skip a step, do I have to rename the folder I extracted the zip into? Sorry if this is a really obvious question, I'm an idiot when it comes to this kind of stuff.

**Comment by iep1000** [comment]
This is how I'm imputting it into the terminal. 
firstname@computername ~ % /Users/firstname/Downloads/zulu16.30.15-ca-fx-jdk16.0.1-macosx_x64  -jar mcaselector-1.16.2.jar 

It usually gives me the "no such user" message or "permission denied" message

**Comment by Querz** [comment]
you need to drag and drop `zulu-16.jdk/Contents/Home/bin/java` from the extracted folder into your terminal, not the entire extracted folder. So your command would look similar to this:
`/Users/firstname/Downloads/zulu16.30.15-ca-fx-jdk16.0.1-macosx_x64/zulu-16.jdk/Contents/Home/bin/java -jar mcaselector-1.16.2.jar`.

**Comment by iep1000** [comment]
Still won't work. I'm happy to keep using an older version of mcaselector for now. I tried 1.15 and it still functions with my world. 

![Screen Shot 2021-06-17 at 22 22 15](https://user-images.githubusercontent.com/65983741/122496964-a55af380-cfba-11eb-96d2-fa63f2edd1ee.png)

**Comment by narcarsiss** [comment]
> Still won't work. I'm happy to keep using an older version of mcaselector for now. I tried 1.15 and it still functions with my world.
> 
> ![Screen Shot 2021-06-17 at 22 22 15](https://user-images.githubusercontent.com/65983741/122496964-a55af380-cfba-11eb-96d2-fa63f2edd1ee.png)

Make sure your command "-jar" is using a Hyphen " - "not a  " ~ "

can you also confirm in Terminal that the command  "java" gives a version?

**Comment by iep1000** [comment]
Well I'm the biggest moron it was just that I was using the "~" and not the hyphen. Sorry.

**Comment by narcarsiss** [comment]
Glad we could help :)
