### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by LovesAsuna** [Querz/mcaselector#23]
This software is very good. I want to repost it to the Chinese forum,and I will translate it into Chinese and hope to get your consent.

**Comment by Querz** [comment]
Thanks! I have been working on a dynamic translation system recently and pushed those change to master now.
If you want to translate the program, you can create a pull request to add a chinese language file to https://github.com/Querz/mcaselector/tree/master/src/main/resources/lang .
Also feel free to post it on your forum, as long as the download link leads to https://github.com/Querz/mcaselector/releases .

**Comment by LovesAsuna** [comment]
[zh_CN.txt](https://github.com/Querz/mcaselector/files/3364532/zh_CN.txt)

**Comment by Querz** [comment]
Thank you very much!
[Release 1.7.2](https://github.com/Querz/mcaselector/releases/tag/1.7.2) is out now with the translations. Have fun!

**Comment by LovesAsuna** [comment]
you are welcome

**Comment by LovesAsuna** [comment]
![H6P0(73%@5L)$%A3X{Q$FM1](https://user-images.githubusercontent.com/32810896/60757740-fc22c900-a040-11e9-8675-f32f0554eb88.png)
Is this translation wrong?

**Comment by Querz** [comment]
Oh oops, my bad. I fixed that and a crash in the progress dialogs resulting from the recent changes.

I added a few more lines to the language files, do you mind translating those to Chinese? Thanks!

```
dialog.progress.title.deleting_selection;Deleting selection...
dialog.progress.title.exporting_selection;Exporting selection...
dialog.progress.title.importing_chunks;Importing chunks...
dialog.progress.title.deleting_filtered_chunks;Deleting filtered chunks...
dialog.progress.title.exporting_filtered_chunks;Exporting filtered chunks...
dialog.progress.title.selecting_filtered_chunks;Selecting filtered chunks...
dialog.progress.title.changing_nbt_data;Changing NBT data...
```

**Comment by LovesAsuna** [comment]
sure.I am glad to translate it,just a little.I originally want to modify my translation.But now it is night in china,i have to sleep.i will give you the new translation tomorrow.

**Comment by LovesAsuna** [comment]
[zh_CN.txt](https://github.com/Querz/mcaselector/files/3365230/zh_CN.txt)
This is the new version of translation.

**Comment by Querz** [comment]
Thanks!
I updated release 1.7.3 to include those translations.
