### ISSUE TITLE
Question: Is there a way to select a specific height to reset ? like i want to reset everything under my base.

### ISSUE THREAD

**Issue by SncwFace** [Querz/mcaselector#230]

**Comment by Querz** [comment]
Yes, but you will have to insert something else too. Minecraft isn't really made to partially regenerate chunks. There is a way to reset a chunk only partially and tell Minecraft to regenerate it, but it will also mess with the remaining blocks that you intend to keep.

You can find a more in-depth explanation [here](https://gist.github.com/Querz/008111195cc7bc012bb291849d2eb9c7).
