### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by GauntAndreX8** [Querz/mcaselector#232]
How do you download and install is too confusing and instructions are not to clear and tutorial videos I look at online are useless not teaching me to get install

**To Reproduce**

**Expected behavior**

**Screenshots and other files**
Relevant world files ('.mca'-files) and selection files ('.csv'.files) must be bundled in a '.zip'-archive.
To create the 'debug.log' file, follow these steps:
1. Enable 'Print debug messages' in 'File'-->'Settings'.
2. Restart MCA Selector.
3. Reproduce the problem.
4. Close MCA Selector and attach the 'debug.log' file to this bug report.

**Environment (please complete the following information):**
- OS: [e.g. Windows 10]
- Java version: [e.g. 1.8.0_202 and no, "newest version" is not a version]
- Version [e.g. 1.9.8]

**Additional context**
Add any other context about the problem here, e.g.:
- Minecraft version used to generate affected parts of your world.
- Relevant debug messages from Minecraft.
- Mods used that change Minecraft save files or add blocks to the game.
- Previously used programs to alter the world files.

**Comment by bc-185** [comment]
You should download the [Windows Installer](https://github.com/Querz/mcaselector/releases/download/1.16.2/MCA_Selector_Setup.exe). It will get everything ready for you. MCA Selector requires Java 16 with JavaFx, which you probably don't know how to install.

**Comment by GauntAndreX8** [comment]
Oh ok thxs
