### ISSUE TITLE
Javafx

### ISSUE THREAD

**Issue by Mr-Frimman1** [Querz/mcaselector#238]
So I have been using mcaselector for a while and now after upgrading to java 16.0.1 it gives me the following error after running this command to start it up "java -jar /home/ahmed/Downloads/mcaselector.jar" 
The error: Missing JavaFX, please install javaFX for your java version (16.0.1) to use MCA selector.
What I have tried to the moment:
1-install javaFX via "sudo pacman -S  java-openjfx"
2-install javafx via the method showed in https://openjfx.io/
Systme info:
os: arch linux with kde plasma
laptop : toshiba Z30-c-Z01
thanks in advance

**Comment by Querz** [comment]
please refer to https://github.com/Querz/mcaselector#when-you-receive-an-error-from-a-previously-installed-version-of-java for this kind of error.

**Comment by Inhibit** [comment]
The instructions are under "Installation" and have moved here: https://github.com/Querz/mcaselector/wiki/Installation for the next person having trouble with manually installing JavaFX libraries and getting them to play nicely.
