### ISSUE TITLE
Feature request: section-level operations for 1.18 merges

### ISSUE THREAD

**Issue by Artoria2e5** [Querz/mcaselector#241]
The upcoming 1.18 version provides extra underground space, and I am one of these people very interested in shoehorning the new underground into my existing chunks by splicing at y=15 or something to get the extra deep space.

As a result, I am going to need copy-and-paste on a more granular level than the chunk -- the 16x16x16 sections in the chunk file format might be just the level I need.

**Comment by Querz** [comment]
Importing a range of sections is already possible. The syntax is explained [here](https://github.com/Querz/mcaselector#chunk-import).
[Here](https://gist.github.com/Querz/008111195cc7bc012bb291849d2eb9c7) you can find a documentation with an example on how to apply this to a world.

**Comment by Artoria2e5** [comment]
So it does regenerate empty sections! Awesome.

**Comment by Querz** [comment]
Not really. If you set the `Status` to `empty` it will regenerate *all* solid blocks in the chunk, not just the ones in missing sections, overwriting potential builds. I recommend sticking with the method where you import existing sections from one world into another.
