### ISSUE TITLE
Nether rendering as gray (no detail) in 1.16.x

### ISSUE THREAD

**Issue by drnixon** [Querz/mcaselector#243]
No issues with render in 1.15, but any version of 1.16 that I have tried on the same worlds fail to render the nether. All displayed chunks are gray, with occasional red blips.

**To Reproduce**
1. Open world in 1.16.x
2. Select DIM-1
3. See error in render.

**Expected behavior**
Dimension should render in same detail as overworld/DIM1, as it did in prior versions of mcaselector.

**Screenshots and other files**
Screenshot attached is the same world, DIM-1, opened simultaneously in mcaselector 1.15 and 1.16.3. DIM-1 is the only dimension that shows this erroneous rendering. I have to use 1.15 if making changes to DIM-1.
<img width="803" alt="Screen Shot 2021-07-21 at 2 54 43 PM" src="https://user-images.githubusercontent.com/50930574/126551938-f839203d-700c-41e4-8a7a-59fc76cef2e7.png">

**Environment (please complete the following information):**
- OS: macOS 11.4
- Java version:
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9)
OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode, sharing)
- Version of MCA Selector: Same behavior in 1.16.2 and 1.16.3

**Additional context**
World from screen shot above rendered in a mix of Minecraft versions (DIM-1 generated originally in 1.15, individual chunks in subsequent versions). Have tested it on worlds generated in 1.12, 1.13, 1.15, 1.16 and 1.17. Same render issues.

**Comment by vaughner81** [comment]
That grey rendering is actually a map of the nether ceiling.  If you look close you can see the mushrooms that have spawned up there.

**Comment by drnixon** [comment]
Well, that's... weird. Confirmed by dropping into spectator mode, those gray/red areas correspond to mushrooms on the Nether roof. Which means something between 1.15 and 1.16 completely changed how mcaselector determines what X height to choose for renders in the Nether. Any potential fix for that?

**Comment by Matej-Hajek** [comment]
There is a Slider at the top right(at your picture showing "319"). You can move it to the lower attitude

**Comment by drnixon** [comment]
Well now I feel silly. I never noticed that was added in 1.16. Thanks.
