### ISSUE TITLE
Can't Load in Nether Maps

### ISSUE THREAD

**Issue by JediM4ster** [Querz/mcaselector#249]
I created a build in the nether and I wanted to downsize the map, but whenever I select it as a world to load it in, it shows up as all gray and weird.

**Comment by Matej-Hajek** [comment]
#### hello, check [https://github.com/Querz/mcaselector/issues/243](url)
You have a **slider** at the **top right** corner in mcaselector, you can move it to like 85 to see the nether tereain.
(*grey and weird = nether ceiling*)
