### ISSUE TITLE
2 questions :)

### ISSUE THREAD

**Issue by Aadi-mone** [Querz/mcaselector#255]
Hello, My Minecraft server is having almost 150 players online in survival and its custom host so we are having issue with Storage, we decided to clean up some unwanted chunks, I watched this video: https://www.youtube.com/watch?v=ADDTXGRJo20
and there he says use inhabited time, but idk whether the players have spent 5 hours or not, so how would I clean up some unused or anarchy type chunks safely? 

2nd:

How to save bruh?

Please help me :)

**Comment by Matej-Hajek** [comment]
You don´t need to save(so make backups of your world)
Try using overlays and filters like `InhabitedTime <= "10 min"` 
Read [Readme.md](https://github.com/Querz/mcaselector/blob/master/README.md)
And join [Discord server](https://discord.com/invite/h942U8U)

**Comment by Aadi-mone** [comment]
You don't need to save?
which means just click delete selected chunks?
and I can't join the discord server for some reason :)

**Comment by Matej-Hajek** [comment]
> You don't need to save?
> which means just click delete selected chunks?
Yes, it is the reason why to backup
