### ISSUE TITLE
Question regarding 1.17 datapack

### ISSUE THREAD

**Issue by coolowe23** [Querz/mcaselector#258]
I have a world that me and me friends have been playing on a world since 1.17 came out and I enabled the Cave and Cliffs preview data pack. I was wondering if in future releases if it would be possible to copy chunks from this world and move them over into 1.18 or any of the snapshots leading up to 1.18.
I saw #254 and understand that mcaselector doesn't work on the snapshots yet due to the changes being made to chunks. But will future changes being made to the software to handle any changes made with the Caves and Cliffs data pack. Assuming the datapack is just the y level changes my world goes from -64 to 319 just like the ranges in mcaselector. Or, is copying the chunks to the newer version too specific case and it wont be able to be copied?
Thank you!

**Comment by coolowe23** [comment]
Closed, the world seems to load just fine in snapshot 21w39a

**Comment by boasbakker** [comment]
Ehm does it? It doesn't work for me

**Comment by coolowe23** [comment]
@boasbakker 
Yeh for some reason it seemed to load fine for me. But you also have to remember to take out the datapack before you load in the world on the snapshot or else it won't work.

**Comment by coolowe23** [comment]
If you're also referring to the world not loading in mcaselector. There should be a dev preview version in the discord that handles loading the snapshot worlds.

**Comment by boasbakker** [comment]
Oh thanks. Yeah I knew you could update old worlds to this snapshot, that is intentional. I was refering to the world not loading
