### ISSUE TITLE
`Config.getEnvFilesWithDefault()` choking on non-dangling symlinks

### ISSUE THREAD

**Issue by AviKav** [Querz/mcaselector#265]
**Describe the bug**
`Config.getEnvFilesWithDefault()` chokes on non-dangling symlinks

**To Reproduce**
Run MCA Selector with `~/.cache` (or probably any component within `~/.cache/mcaselector`, `~/.local/share/mcaselector`, or `~/.mcaselector/mcaselector`) as a non-dangling symlink (And probably dangling symlinks too (Now should *those* be handled? :) ))

**Expected behavior**
A process alive for more than ~60ms (Also no stacktrace. (And no crashing. (Did I mention no crashing?)))

**Screenshots and other files**
```
$ /mnt/applications/zulu16.30.15-ca-fx-jdk16.0.1-linux_x64/bin/java -jar /mnt/applications/MCA/mcaselector-1.16.3.jar
failed to create directory /home/avi/.cache: /home/avi/.cache
Exception in thread "main" java.lang.ExceptionInInitializerError
        at net.querz.mcaselector.debug.Debug.dumpf(Debug.java:59)
        at net.querz.mcaselector.Main.main(Main.java:17)
Caused by: java.lang.RuntimeException: failed to create directories for mcaselector, please check permissions for /home/avi/.cache
        at net.querz.mcaselector.Config.getEnvFilesWithDefault(Config.java:102)
        at net.querz.mcaselector.Config.<clinit>(Config.java:56)
        ... 2 more
$ ll /home/avi/.cache /mnt/applications/cache/xdg-cache -d
lrwxrwxrwx 34 avi avi  7 May 12:16 /home/avi/.cache -> /mnt/applications/cache/xdg-cache
drwxrwxr-x  - avi avi 13 Oct 19:37 /mnt/applications/cache/xdg-cache
```

**Environment (please complete the following information):**
- OS: Void Linux
- Java version: `OpenJDK Runtime Environment Zulu16.30+15-CA (build 16.0.1+9)` (The JavaFX cdn link from the README 'cause I could not find it on their download page for the life of me)
- Version of MCA Selector: 1.16.3

**Additional context**
Relevant codepath:
`Config.getEnvFilesWithDefault(...)`
-> `attemptCreateDirectory(...)`
-> `java.nio.file.Files.createDirectories(...)`
-> `createAndCheckIsDirectory(...)`
-> `isDirectory(dir, LinkOption.NOFOLLOW_LINKS)`

**Comment by Querz** [comment]
Fixed in [release 1.17](https://github.com/Querz/mcaselector/releases/latest).
