### ISSUE TITLE
Nothing gets selected when selection radius is set

### ISSUE THREAD

**Issue by skerit** [Querz/mcaselector#268]
**Describe the bug**

When I set the `Selection radius` in the `Filter chunks` window, nothing actually gets selected.
When I unset the `Selection radius` again, it works as it should.

**To Reproduce**
1. Go to 'Tools » Filter chunks'
2. Set the actual filters
3. Enter a value in the `Selection radius`
4. Click OK
5. See that nothing gets selected

**Expected behavior**

It should select the chunks that correspond with the filter + the ones in a radius around it.

**Screenshots and other files**
![image](https://user-images.githubusercontent.com/755212/138451270-e04b673d-50bd-4893-9dde-b91d42aab938.png)

**Environment (please complete the following information):**
- OS: Linux (Manjaro - Gnome Shell)
- Java version: 16.0.1
- Version of MCA Selector: 1.16.3

**Comment by Querz** [comment]
Fixed in [release 1.17](https://github.com/Querz/mcaselector/releases/latest).
