### ISSUE TITLE
Program doesn't launch

### ISSUE THREAD

**Issue by TheWaffleLord** [Querz/mcaselector#276]
**Describe the bug**
When opening "MCA Selector.exe" from the folder the installer (MCA_Selector_Setup.exe) creates if it was installed into a folder starting with "!" ("!Minecraft Stuff" for example), the program opens and immediately closes. (Can be seen open for a split second in the task manager)

**To Reproduce**
1. Make a folder starting with "!" ("!Minecraft Stuff" for example);
2. Install MCA Selector in that folder;
3. Run "MCA Selector.exe";

**Environment**
- OS: Windows 7 Home Premium
- Java version: Java 8 Update 311 | Version 8.0.3110.11
- Version of MCA Selector: mcaselector-1.17

**Additional context**
When installed into a folder that doesn't start with "!" the program opens and works fine.

**Comment by Querz** [comment]
I managed to fix the issue where the `!` is at  the beginning or anywhere *in* the folder names (see https://github.com/Querz/mcaselector/commit/755f382ae8da8f13b8061cb8bc5946dcb2a74dce), but there is no elegant solution for when the `!` is at the end of the folder name, e.g. `C:\Users\blah\MCA Selector!\`.
This is actually a bug in the standard library when a resource is loaded from a jar file: https://bugs.openjdk.java.net/browse/JDK-4523159
This bug will probably not be fixed soon, judging from the fact that this issue has been open for over 20 (!) years.
