### ISSUE TITLE
[new feature] Add circular selection (centerX;centerZ;radius) to filtering tools

### ISSUE THREAD

**Issue by gmfamily** [Querz/mcaselector#277]
Your tool is very nice and powerfull :) It is already an essential piece of our world upgrade strategy to 1.18/1.19!
Is it possible to add a circular selection option (defined in chunks coords should be sufficient to support our needs) like illustrated below:

||0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|
|---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|0|-|-|-|-|-|+|+|+|+|+|-|-|-|-|-|
|1|-|-|-|+|+|+|+|+|+|+|+|+|-|-|-|
|2|-|-|+|+|+|+|+|+|+|+|+|+|+|-|-|
|3|-|+|+|+|+|+|+|+|+|+|+|+|+|+|-|
|4|-|+|+|+|+|+|+|+|+|+|+|+|+|+|-|
|5|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|
|6|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|
|7|+|+|+|+|+|+|+|C|+|+|+|+|+|+|+|
|8|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|
|9|+|+|+|+|+|+|+|+|+|+|+|+|+|+|+|
|10|-|+|+|+|+|+|+|+|+|+|+|+|+|+|-|
|11|-|+|+|+|+|+|+|+|+|+|+|+|+|+|-|
|12|-|-|+|+|+|+|+|+|+|+|+|+|+|-|-|
|13|-|-|-|+|+|+|+|+|+|+|+|+|-|-|-|
|14|-|-|-|-|-|+|+|+|+|+|-|-|-|-|-|

Selection from center (posX=7; pos2=7; radius=7) - Units are chunk number / position (Yes, I like the number 7;))

**Comment by Querz** [comment]
Circle filters has been added in [release 1.17.1](https://github.com/Querz/mcaselector/releases/latest)
