### ISSUE TITLE
MCA selector unable to display chuncks in worlds upgraded to 1.18 from a prior Minecraft version unless those chuncks are explored again and re-rendered in game.

### ISSUE THREAD

**Issue by ArcherLegend** [Querz/mcaselector#300]
If you have a world which was started in a Minecraft version which was prior to 1.18 such as 1.17 or 1.16.5 and then you upgrade your world to 1.18 or 1.18.1 MCA selector is unable to render the map of the world and displays the region squares as black unless you go inside your world and re-explore the already explored chuncks.

To reproduce the issue it is sufficient to start a world in 1.16.5 and explore it a bit and use MCA selector to wiew the map. After upgrading the world to 1.18 open MCA selector without opening the world and all the explored chuncks will not be rendered in the map but they will just be black squares. Then open the world upgraded to 1.18 and after looking around for a little bit use MCA selector to wiew the map of the chuncks: only new chuncks or existing chuncks that have been re-rendered are correctly displayed whereas the others remain black squares till you explore them again.

- OS: Windows 10 21h2
- Java version: 8 and 16 for Minecraft 1.16.5 and 1.17.1 and then 17 for Minecraft 1.18 and 1.18.1
- Version of MCA Selector: 1.17.1

**Comment by Querz** [comment]
Fixed in [release 1.17.2](https://github.com/Querz/mcaselector/releases/tag/1.17.2)

**Comment by ArcherLegend** [comment]
Thank you for fixing the bug. Happy new year!
