### ISSUE TITLE
Red ''error'' chunks when opening the nether dimension in 1.18 worlds using MCA Selector 1.17.1

### ISSUE THREAD

**Issue by Fauvic** [Querz/mcaselector#301]
**Describe the bug**
The chunks in any Nether (DIM-1) 1.18 dimensions opened, either 1.17 converted worlds or newly created worlds, contain red ''error'' chunks.

**To Reproduce**
1. Create a world in 1.18
2. Enter a nether portal for 1st time
3. Exit world
4. Open the nether dimension in MCA Selector 1.17.1

**Expected behavior**
No red ''error'' chunks. I'm not sure if this is only on my end, if it's only a incompatibility issue with 1.18 worlds in MCA Selector, or if these chunks have an actual issue. Refer to below context regarding RAM usage.

**Screenshots and other files**

Screenshot:
![Screenshot 2021-12-11 135915](https://user-images.githubusercontent.com/2331408/145675709-48b0e95c-b22c-416a-9af1-1dca64c6bb16.png)

World file:
[New World Nether Test.zip](https://github.com/Querz/mcaselector/files/7696934/New.World.Nether.Test.zip)

Debug:
[debug.log](https://github.com/Querz/mcaselector/files/7696936/debug.log)

**Environment (please complete the following information):**
- OS: Windows 10
- Java version: 16.0.1
- Version of MCA Selector: 1.17.1

**Additional context**
Add any other context about the problem here, e.g.:
- I noticed that the server is using much more RAM than previously, even if no players are in there. When I delete the nether dimension from the save file and restart the server, the RAM usage normalises (until a new ''corrupted'' nether is loaded for 1st time).
- Minecraft version used to generate affected parts of your world: 
- Mods used that change Minecraft save files or add blocks to the game: Tried on both modded fabric and vanilla

**Comment by Querz** [comment]
Fixed in [release 1.17.2](https://github.com/Querz/mcaselector/releases/tag/1.17.2)
