### ISSUE TITLE
MCA Selector crashes on load (fatal error) - Mac M1 needs updated JavaFX to fix

### ISSUE THREAD

**Issue by drnixon** [Querz/mcaselector#302]
macOS 12.0.1, M1 processor, mcaselector 1.17.1. MCA Selector briefly opens on launch then immediately crashes with an error referencing SafeFetchN. Same issue with multiple other older tested versions of MCA Selector and/or Java SDK.

Looks like it's a bug in JavaFX on M1 processors, fixed in JavaFX 17.0.2 - but that's not released until January. To get it to run users will need to replace JavaFX with the 17.0.2-ea+1 early access version, at least until 17.0.2 is released to relevant Java JDK.

**Comment by drnixon** [comment]
Filing bug more as an FYI. Not something that can be fixed by Querz but if others get the issue, the above will correct it.

**Comment by Nico314159** [comment]
JavaFX 17.0.2 is out now, but I am still experiencing this same issue
