### ISSUE TITLE
Can't set biomes to nether wastes

### ISSUE THREAD

**Issue by Jason-Silla** [Querz/mcaselector#319]
I want to set a nether waste (which was messed up in a conversion between bedrock to java and is now plains) to the nether waste biome. It keeps setting the biome to plains! I know this isn't because of the editor not working because using the filter feature to check for a specific biome after the changing of biome there is no "plains" biome in the entire nether.

**To Reproduce**
1. Go to any biome and select an area in MCASelector
2. Click on Tools/Change Fields
3. Change biome to nether (this should be nether_wastes, which I assume is causing the issue)
4. Exit the world in MCASelector
5. Log into the world on Minecraft Java and go to the area you just edited.
6. Check F3 Menu to see biome is plains

**Expected behavior**
The biome should have changed from whatever biome (in my case corrupted nether waste) to nether_waste. However, what ends up happening is it changes to plains. I think it's because it is just nether, not nether_wastes and when you log into the world, the game defaults the biome to plains.

**Screenshots and other files**
![Screen Shot 2022-01-11 at 11 05 36 AM](https://user-images.githubusercontent.com/92275622/148978243-515f5247-7042-4835-95bf-aa3074a7cc72.png)

**Environment (please complete the following information):**
- OS: MacOS Monterey M1 Chip
- Java version: 1.18.1
- Version of MCA Selector: 1.17.2 Universal

**Additional context**
- I use OptiFine and Replay Mod using forge.
- I have used Amulet Map Editor to try and change the biome and they have the same bug as this one.

**Comment by Insprill** [comment]
Are you setting it to `nether` or `nether_wastes` in MCA? Setting a biome to `nether_wastes` works fine for me on MCA 1.17.2 / MC 1.18.1.

**Comment by Jason-Silla** [comment]
> 

Ya I only put “nether_waste”. You need to put “nether_wastes”. My mistake sorry.
