### ISSUE TITLE
Remove JavaFX support

### ISSUE THREAD

**Issue by Atten007** [Querz/mcaselector#331]
**Describe the bug**
I can't open this application because it tells me to use JavaFX which is only compatible with apple silicon MacBooks and not with Intel x64/x86 MacBooks and it's very useless!

**To Reproduce**
1. Download it
2. Try to open it
3. It will not work because JavaFX is required

**Expected behavior**
I thought that I can open it without JavaFX

**Screenshots and other files**
Relevant world files ('.mca'-files) and selection files ('.csv'-files) must be bundled in a '.zip'-archive.
To create the 'debug.log' file, follow these steps:
1. Enable 'Print debug messages' in 'File'-->'Settings'.
2. Restart MCA Selector.
3. Reproduce the problem.
4. Close MCA Selector and attach the 'debug.log' file to this bug report.

**Environment (please complete the following information):**
- OS: macOS Big Sur
- Java version: newest Version
- Version of MCA Selector 1.17.2

**Additional context**
Add any other context about the problem here, e.g.:
- Minecraft version used to generate affected parts of your world.
- Relevant debug messages from Minecraft.
- Mods used that change Minecraft save files or add blocks to the game.
- Previously used programs to alter the world files.

**Comment by supersaint7780** [comment]
javaFX is a cross platform UI library built using Java. It is available for Intel Mac also. You may check it on their website. Earlier it used to be a part of jdk but now it is distributed separately as its own sdk.

**Comment by Uguisu32J** [comment]
Currently there is no mac app package...

**Comment by Querz** [comment]
I added the download link for the zulu JRE for Apple M1 chips to the Wiki.
