### ISSUE TITLE
Clearing the cache shouldn't clear the selection

### ISSUE THREAD

**Issue by oskarkk** [Querz/mcaselector#335]
**Describe the bug**
Clearing the cache clears the selection. This shouldn't happen. I was selecting parts of my world and noticed that some renders were out of date, so I cleared the cache and by doing that I lost my quite complex selection and had to select everything again.

**To Reproduce**
1. Select a part of world
2. View > Clear cache
3. Selection gone

**Expected behavior**
Clearing the cache should only update the render, it shouldn't do anything to selection.

**Environment (please complete the following information):**
- Manjaro Linux
- Java 16
- MCA Selector 1.17.2

**Comment by Querz** [comment]
fixed in version 2.0.
