### ISSUE TITLE
Attempting to run in archlinux results in the software crashing

### ISSUE THREAD

**Issue by Da-Boom** [Querz/mcaselector#339]
Java Version: `jre-openjdk 17.0.3.u3-1`
JavaFX Version: `java-openjfx 17.0.3.u0-1`

- as you can see, near enough the same version that it should work fine
  
McaSelector Version - mcaselector-1.17.2.jar

Commandline to launch 
`java -jar mcaselector-1.17.2.jar --module-path "/usr/lib/jvm/java-17-openjdk/lib/" --add-modules ALL-MODULE-PATH`

The Software crashes with this response:

`failed to create directory /etc/xdg/mcaselector: /etc/xdg/mcaselector(AccessDeniedException)`
`failed to create directory /etc/xdg/mcaselector: /etc/xdg/mcaselector(AccessDeniedException)`
`[17:26:05.973] error: missing mode`

From these lines alone, This appears to be trying to use the system default xdg location for xdg configurations as specified in `$XDG_CONFIG_DIRS`  (which if unspecified in the environment variables, should default to `/etc/xdg/`) instead it should default to the user configuration directory as specified in `$XDG_CONFIG_HOME`  which if unspecified should default to `$HOME/.config/` - with `$HOME` being an environment variable defined upon user login to identify what and where the user's home directory is.

`$HOME/.config` is pretty much the linux version of `%appdata%` with the alternative directory being `$HOME/.local/share/`

As you can see, this is resulting in a permissions error - the permissions of `/etc/xdg/` make it so that that directory can only be written by its owner, which is the root user, or the system administrator account, and it makes no sense to write files that have to do with a piece of user software in a system configuration directory

I have seen this issue pop up in closed bug reports like report #285 - but this is unique as i am not using an incorrect or incompatible version of java or javafx - both of these are the latest from the official archlinux repository and should work fine together. It might have something to do with my XDG desktop configuration (running XFCE4) but all my XDG configs are the default for this window manager anyway.

**Comment by Querz** [comment]
Make sure to add the `--module-path` and `--module-info` parameters to the `java` command. If you add them *after* `-jar mcaselector-1.17.2.jar` they are treated as program arguments for MCA Selector, not as parameters for the JVM (hence the `error: missing mode` because MCA Selector requires some specific parameters to run in CLI mode).

**Comment by Da-Boom** [comment]
OK fixed it, turns out i had 2 issues. Number 1 was exactly what you said. Issue 2, relates to the fact that archlinux installed the javafx library files directly into `/usr/lib/jvm/java-17-openjdk/lib/  - meaning when you try to include just the `lib` folder, it includes the base JDK libraries twice, causing them to conflict with themselves  - so my launch arguments ended up needing include each `.jar` file for javafx manually

`export JAVA_LIBS = /usr/lib/jvm/java-17-openjdk/lib`
`java --module-path $JAVA_LIBS/javafx.base.jar:$JAVA_LIBS/javafx.graphics.jar:$JAVA_LIBS/javafx.controls.jar:$JAVA_LIBS/javafx.swing.jar:$JAVA_LIBS/javafx.fxml.jar:$JAVA_LIBS/javafx.media.jar:$JAVA_LIBS/javafx-swt.jar:$JAVA_LIBS/javafx.web.jar --add-modules ALL-MODULE-PATH -jar mcaselector-1.17.2.jar`
