### ISSUE TITLE
[Enhancement] Delete entities too when deleting chunks

### ISSUE THREAD

**Issue by Notoriousi** [Querz/mcaselector#353]
**Describe the bug**
Not a bug, enhancement

Make MCA Selector have an option when deleting chunks to also delete the POI's and Entities. This will prevent duplicating entities or when for example the world changes to prevent entities from just falling and dying. (or suffocating)

**Comment by Querz** [comment]
MCA Selector does that already. You probably used `Open Region` before to open your world, which has now been removed in version 2.0 to avoid confusion. `Open world` detects the world's `region`, `poi` and `entities` folders automatically and incorporates them in those operations.
If the `poi` and `entities` folders are for some reason named differently for your world (maybe a mod changed the names or the paths), they can still be manually adjusted in `File --> Settings --> World`.
