### ISSUE TITLE
[Feature Request] Radius Filter

### ISSUE THREAD

**Issue by carthradge4** [Querz/mcaselector#356]
Some other MC tools have a radius filter, and I find it very useful. It would work like the current coordinate filters but would check one radius (euclidean distance).

For our server, for example, we use radius limits between updates, This greatly help us filter and delete low inhabited chunks outside of a given radius while keeping chunks inside the radius unchanged.

**Comment by HoldYourWaffle** [comment]
I might be misunderstanding you, but isn't this what the 'Circle' filter is for?

**Comment by Querz** [comment]
The Circle filter does this:

- Creates a circular selection starting at a center point with a specific radius. Syntax: `<center-x>;<center-z>;<radius>`. The center coordinates are chunk coordinates and the radius is measured in chunks. Multiple circles can be chained with a comma (,).
