### ISSUE TITLE
Are modded blocks supported?

### ISSUE THREAD

**Issue by mimi-min** [Querz/mcaselector#380]
Hello,

First of all, thank you for this wonderful tool. You've honestly saved me so many hours of recreating builds!

However I'm having an issue that I didn't notice before, maybe it was before I was using mods... basically, when I export and import chunks into another world, then load the world on my server, any blocks that came from mods are missing (ex. Biomes O' Plenty, etc).

I searched around for an answer but couldn't find anything, so I figured I would just ask; does MCA Selector have support for modded blocks? Is there something I'm missing, or is this behavior to be expected?

Thank you!

**Comment by mimi-min** [comment]
Actually, I tried it again and it seems to have worked okay. 

I guess I must have accidentally pasted it into a non-modded world first when I was testing, so tgs blocks got removed.

Thanks again!

**Comment by ReiNerd06** [comment]
Olá, eu tenho um mapa que utiliza o mod ATG para gerar o mundo do minecraft e por um descuido o mapa ficou com geraçao padrao do minecraft só que eu fiz utilizando o programa a alteraçao dessa geraçao padrao para a do ATG por meio da importaçao de chunks opçao do programa e funcionou, entretanto o blocos dos mods dessas chunks importadas estao totalmente bugados e com lag absurdo. Gostaria de saber se tem como resolver isso!
