### ISSUE TITLE
Support for modded blocks for the ReplaceBlocks feature under Change NBT.

### ISSUE THREAD

**Issue by whatisagoodusername5256** [Querz/mcaselector#387]
I think it would be a nice feature to be able to replace modded blocks as well. At least to be able to replace them with vanilla blocks.

Example: ReplaceBlocks = "create:gabbro=minecraft:stone"

This would be useful for those who are updating a world with a lot of blocks that disappear when updating a modpack to a different version because the block in question is no longer supported/removed.

If more is needed than the block id, then obviously this might not be possible, but thanks for considering the suggestion at least either way.

**Comment by arvitus** [comment]
I just copied this message by Querz from discord:

you can replace blocks with the `ReplaceBlocks` field in the `Change fields` dialog. The syntax works like this: `<source-block>=<target-block-name|block-nbt[;<tile-nbt]>`. if the source block is *not* a valid minecraft block name, you can use single quotes to force it to validate. everything in single quotes is also interpreted as a regular expression. so for example if you would like to replace *all* kinds of `log` with let's say, `stone`, you could do something like this: `'.*log$'=stone`

**Comment by whatisagoodusername5256** [comment]
That did exactly what I needed! Thanks! Guess I should close this feature request since it effectively exists already.
