### ISSUE TITLE
Question on using this to update world for 1.14

### ISSUE THREAD

**Issue by Inazumaa** [Querz/mcaselector#4]
Hi,
1.14 just came out and I've been searching for a tool that will delete chunks on my current 1.13 world so that when I load it in 1.14, new chunks will generate with all the new features (such as new biomes, villager architecture, etc). Will this tool be able to do that?

**Comment by Querz** [comment]
@Inazumaa Deleting chunks in 1.13 worlds and then updating to 1.14 should work. I didn't do extensive testing changing 1.14 worlds yet, but everything seems to work fine so far, there were no substantial changes in the file structure of mca files like we had in 1.13.

Everything the MCA Selector deletes will be regenerated by Minecraft, as soon as you make it load those chunks.

**Comment by Zitchas** [comment]
Thanks for answering this question. 

As a side note, someone linked to this on Reddit, so you might be getting a bit more traffic. I'd never heard of this program until today, but it looks really useful (I've been doing some of this stuff manually for years. Having something to do it in a much more intuitive manner looks VERY useful!)

**Comment by Overdoziz** [comment]
Hey there, I've been trying to do something similar, but with a world that was generated in 1.13, but has been played on with the 1.14 update. I'm not sure if it recognizes chunks that I've been in since the 1.14 update, though. Those regions don't show up (or are simply entirely black), but the regions that I haven't revisited since the update show up fine. I tried with an older version of the map (1.13) and that one showed everything just fine. 

Anything I can do on my side to fix that or no?

**Comment by Querz** [comment]
I published release [1.6](https://github.com/Querz/mcaselector/releases/tag/1.6) which adds support for Minecraft 1.14 worlds and fixes the issue that some chunks would not appear.

**Comment by Overdoziz** [comment]
Awesome, great job!

**Comment by JAVR86** [comment]
Is there a way to navigate through the chunks? If i zoom in, i'm unable to move the map to see other chunks closer. I'm trying to not erase buildings.

**Comment by Querz** [comment]
You can move the map by either pressing your middle mouse button or if you are on a Mac by holding `CMD` and using your left mouse button.

**Comment by JAVR86** [comment]
Tool is loading my the map, i can select whatever chunks i want to delete, but the options are not working for me. If I go to Selection ->Delete selected chunks, it doesnt do anything. Tried using also shortcuts. Nothing in the menu bar seems to be working for me. Running the latest JAVA version. My world is a MC Realm already in 1.14. Don't have a 1.13 backup.

**Comment by Querz** [comment]
* What exactly is your "latest Java version"? That version might not be the "latest Java version" anymore tomorrow :)
* What OS are you using?
* What version of the MCA Selector are you using?
* If you enable debug mode, could you send me the console output when this happens?

Thanks!
