### ISSUE TITLE
1.20 support is missing

### ISSUE THREAD

**Issue by Atten007** [Querz/mcaselector#414]
**Describe the bug**
Hello! The update 1.20 hs been released at 5 o' clock PM and it isn't currently available in MCASelector. Can support for this be added?

**To Reproduce**
Nothing

**Expected behavior**
Support for 1.20 is available.

**Screenshots and other files**
Not applicable

**Environment (please complete the following information):**
OS: macOS 14 Sonoma
Java: 17.0.7
MCASelector version: 2.2

**Additional context**
Nothing

**Comment by Querz** [comment]
updated the readme: https://github.com/Querz/mcaselector#supported-versions
