### ISSUE TITLE
Import chunks into "selection only"

### ISSUE THREAD

**Issue by agusfesc** [Querz/mcaselector#42]
Hi, how are you? I try to import chunks and when import  and select the chunks in Offset, the program import the chunks in other chunks not selected. Any help?

**Comment by Querz** [comment]
Good, thanks. Can you post a screenshot of the problem and the settings that caused it (the offset you used and whether the checkbox to overwrite existing chunks was selected)?

**Comment by agusfesc** [comment]
Good, there is no specific error. What happens to me is that I start importing chunks, I select them and when I put the chunks in X and Z and select to replace the existing ones, send the chunks to other chunks that I don't select

**Comment by Querz** [comment]
The MCA Selector does not support importing chunks only into selected chunks.
That seems to be a helpful feature though, I will have a look at it.

For now, you would need to crop the world you want to import to fit into the chunks you want to overwrite.

**Comment by agusfesc** [comment]
Ok, thanks would be a good improvement.

**Comment by Querz** [comment]
[Release 1.9](https://github.com/Querz/mcaselector/releases) adds the option to import chunks into a selection only.
