### ISSUE TITLE
Entities deleted when attempting to clear other chunks

### ISSUE THREAD

**Issue by YaraWhoSees** [Querz/mcaselector#424]
Thank you for your work on this project firstly.

I tried using the MCA Selector to clear all areas inhabited less than 2 minutes on our server, as I am updating it for the new biomes in 1.20. However, a quick check and it had cleared all spawned and named mods, maps, item frames and the like which I only checked at the setup spawn. But this would lead to having to respawn and fix so much for over 30 people on the server, which I kind of don't want to do. When I simply uploaded the unedited world these things were back so it must be something I have done using the tool.

Could you advise me if I should perhaps change what I am uploading from among the world files? I didn't want to chance messing things up by just doing it without checking in.

**Comment by Querz** [comment]
The files that contain world data (terrain, entities, points of interest) are each in a separate folder. Even though the files look the same (all having the `r.x.z.mca` format), they contain different kinds of data.
- `region` contains all terrain data, including biomes, height maps, tile-entities, structure boundaries and proto-chunk data (data being used during the chunk generation process).
- `entities` contains all entity data (mobs, item frames, paintings, items on the ground, ...).
- `poi` contains all points of interest (nether portal locations, villager's workstations).

And a folder containing global data that is not bound to any of the above:
- `data` contains all maps (all files named `map_<id>.dat`), raids, random sequences, ... . MCA Selector does not touch these.

I suspect that you only downloaded the region folder, and therefore don't see the entities while you open the world on your computer, but when you reupload the region folder the old entities are still there.

MCA Selector looks at the `region`, `poi` and `entities` folders and deletes data from all of them when deleting a chunk.

**Comment by YaraWhoSees** [comment]
Thank you for your assistance, this seems to have been what I was doing. I am still learning and was unfamiliar.
