### ISSUE TITLE
World won't load

### ISSUE THREAD

**Issue by SteliosLL** [Querz/mcaselector#43]
I recently read about MCA selector which lets you trim your minecraft world. I downloaded it and decided to give it a try. I loaded my world but the screen didn't change.All i could see were the grid lines. I tried loading different worlds but nothing worked.I didn't get any errors messages. I moved the camera left and right but all i could see were the grid lines. Any ideas about that problem?

**Comment by Querz** [comment]
Are you opening the folder containing the .mca files? What version of Minecraft was the world saved in? Are you using the most recent version of the MCA Selector?

**Comment by SteliosLL** [comment]
I selected the folder and not the "region" folder. OOF i am dumb af
