### ISSUE TITLE
Can't use modded blocks as filters

### ISSUE THREAD

**Issue by Insane96** [Querz/mcaselector#436]
**Describe the bug**
When filtering by blocks/tile entities, you can't use modded blocks.

**To Reproduce**
1. Start a world with a mod that adds at least one block
2. Place that block
3. Run MCA and filter chunks by blocks
4. Can't use the modded block ID because it requires valid vanilla blocks

![image](https://github.com/Querz/mcaselector/assets/7185104/268c40e3-b81f-413f-aa4e-b5680597542c)

**Comment by KateReller** [comment]
https://github.com/Querz/mcaselector/issues/387#issuecomment-1251564787

> I just copied this message by Querz from discord:
> 
> you can replace blocks with the `ReplaceBlocks` field in the `Change fields` dialog. The syntax works like this: `<source-block>=<target-block-name|block-nbt[;<tile-nbt]>`. **if the source block is _not_ a valid minecraft block name, you can use single quotes to force it to validate**. everything in single quotes is also interpreted as a regular expression. so for example if you would like to replace _all_ kinds of `log` with let's say, `stone`, you could do something like this: `'.*log$'=stone`
