### ISSUE TITLE
Question about 1.16

### ISSUE THREAD

**Issue by ardentcrest** [Querz/mcaselector#46]
This could be a silly question, But, Will this be updated to work with 1.16. I have used it for my 1.13.x to 1.14.x world and would love to use it again to clean my world to use in 1.15.x and 1.14.x

**Comment by Querz** [comment]
As long as Mojang does not make any significant changes to how worlds are stored, this should also work for 1.15+. The things that almost always need to be updated for a new Minecraft version is the renderer that creates the top-down view (update the color mapping and how the nether is rendered in 1.16, but those are trivial changes) and the chunk import (when they add entities or tile entities that store some sort of coordinates).

The renderer should also work when it's not updated, but it might display unexpected things.
