### ISSUE TITLE
Change fields and Edit chunk doesn't work with multiple selected chunks

### ISSUE THREAD

**Issue by Dracconis** [Querz/mcaselector#476]
**Describe the bug**
Selecting multiple chunks does not allow for editing the chunks in bulk. Selecting only 1 chunk will allow for editing but whether it is 1 chunk or multiple will not allow for "Change fields"

**To Reproduce**
Steps to reproduce the "Change fields" behavior:
1. Open a World Save and select 1 chunk or multiple chunks
2. Go to Tools
3. Click on Change fields
4. Nothing happens

**To Reproduce**
Steps to reproduce the "Edit chunk" behavior:
1. Open a World Save and select multiple chunks
2. Go to Tools
3. Click on Edit chunk and see that it is greyed out as unusable
4. Nothing happens
 
**Expected behavior**
Expected the ability of times past when the NBT Editor GUI would open allowing for the changing of the fields such as biomes. As it is you have to change 16 different biome fields per chunk when you should be allowed to change 1 biome field for ALL selected chunks. When you need to edit the biomes of 50+ chunks, it gets very tedious and time consuming to have to go through them 1 at a time and change 16 different biome fields to get the expected result.

**Environment (please complete the following information):**
- OS: W10
- Java version: jre17.0.1
- Version of MCA Selector 2.4

**Additional context**
Add any other context about the problem here, e.g.:
- Minecraft version used to generate affected parts of your world.
1.20.4
- Relevant debug messages from Minecraft.
N/A
- Mods used that change Minecraft save files or add blocks to the game.
![image](https://github.com/Querz/mcaselector/assets/28553348/22507d46-d433-4dbe-8318-7c8dcdbaafda)

- Previously used programs to alter the world files.
N/A

**Comment by Querz** [comment]
Probably related to #478, which is fixed in [2.4.1](https://github.com/Querz/mcaselector/releases/tag/2.4.1).
