### ISSUE TITLE
When attempting to select multiple biomes only the last biome in the list is selected

### ISSUE THREAD

**Issue by SReject** [Querz/mcaselector#48]
When attempting to query multiple biomes from a single biome filter, only the last biome in the comma separated list is selected

Example: `snowy_tundra,snow_taiga` only selects snowy_taiga biomes

OS: Win 10 (x64)
Java: v8 (1.8.0_114)
Minecraft: 1.14.4

**Comment by Querz** [comment]
I am sorry, but i can not reproduce this:

`beach`
![Screenshot 2019-10-08 at 08 59 52](https://user-images.githubusercontent.com/8278330/66374003-53bb3280-e9aa-11e9-83d1-758eafc15179.png)

`plains`
![Screenshot 2019-10-08 at 09 00 35](https://user-images.githubusercontent.com/8278330/66374051-67ff2f80-e9aa-11e9-989e-34ca160e1026.png)

`plains,beach`
![Screenshot 2019-10-08 at 09 00 53](https://user-images.githubusercontent.com/8278330/66374080-76e5e200-e9aa-11e9-8428-d12698f8c3ff.png)

`beach,plains`
![Screenshot 2019-10-08 at 09 00 16](https://user-images.githubusercontent.com/8278330/66374097-8402d100-e9aa-11e9-803d-88aac92dff08.png)

Tested on mcaselector-1.8.3 with java 1.8.0_202 and MC 1.14.4.

Are you sure that the world has a `snowy_tundra` as well as a `snowy_taiga` biome?
If you have the time you can also send me a single region file where you encounter this problem.

**Comment by SReject** [comment]
I apologize. I assumed that the comma separated list acted as a `OR` statement where `snowy_taiga,snowy_tundra` meant snowy_taiga OR snow_tundra. Instead it appears such a selector selects overlaps/borders.

May I suggest updating documentation for clarification?

**Comment by Querz** [comment]
I added a note to the readme that makes this clear.
