### ISSUE TITLE
Pressing D + Ctrl while holding D causes makes the program think your still pressing it.

### ISSUE THREAD

**Issue by QazCetelic** [Querz/mcaselector#49]

**Comment by Querz** [comment]
Pressing `D` to move the map view to the right then pressing `Ctrl` to open the "Delete selected chunks" dialog does not stop moving the map view, even after releasing all keys.

--> Will be fixed in the next release

**Comment by Querz** [comment]
This issues has been fixed in [release 1.9](https://github.com/Querz/mcaselector/releases).
