### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by SlideShowGames** [Querz/mcaselector#493]
I have no knowledge of Java so idk how to install JavaFX. I installed openjfx but that didn't do anything so I tried following the javafx setup but it says can't load main class.

I added a bunch of modules because idk what MCASelector needs

```
❯ java --module-path /home/user/Downloads/javafx-sdk-22.0.2/lib --add-modules javafx.controls,javafx.fxml,javafx.base,javafx.web,javafx.swt /home/user/Downloads/mcaselector-2.4.1.jar
Error: Could not find or load main class .home.user.Downloads.mcaselector-2.4.1.jar
Caused by: java.lang.ClassNotFoundException: /home/user/Downloads/mcaselector-2/4/1/jar

```
Im on linux btw

**Comment by Sue1133** [comment]
You can simply use Java with already built-in JavaFX. For example, from here: https://bell-sw.com/pages/downloads/ download the Full JRE version, it already has JavaFX built in.
