### ISSUE TITLE
Improve the installation instructions

### ISSUE THREAD

**Issue by tipeon** [Querz/mcaselector#5]
Hey Querz,

I was reading your installation instructions, and I applied some of that "[brainpower](https://www.youtube.com/watch?v=r2zGcAbXi5g)" as per the requirements section.

I found that downloading a JRE 8+ from Oracle is quite a hassle, and --in most cases-- unnecessary.
In fact, a perfectly suitable JRE can already be found in ``C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64``

I think you could improve the installation instructions with that information.
(but I don't know exactly how ... if I did, I would have created a PR)

**Comment by Querz** [comment]
That's an amazing idea I haven't thought about! I'll add this as soon as i have access to a computer.
