### ISSUE TITLE
Multiple values for parameter world

### ISSUE THREAD

**Issue by Olly32** [Querz/mcaselector#53]
_I've been trying to get this to work for hours. wtf am I doing wrong?_ 
java.exe -jar D:\downloads\mcaselector-1.9.jar --headless --mode select --world C:\Users\Jack\Desktop\nw\paperclip 1.14.2\world --output C:\Users\Jack\Desktop\nw\paperclip 1.14.2\test.csv --query "xPos >= -300 AND xPos <= 300 AND InhabitedTime < 1 hour"
It says "Multiple values for parameter world" no matter what I try.

**Comment by Querz** [comment]
You need to put the path you provided for `--world` in double quotes, because it contains a space.

**Comment by Olly32** [comment]
Thank you
