### ISSUE TITLE
I can't import chunks into a specific world

### ISSUE THREAD

**Issue by BenplayerX** [Querz/mcaselector#62]
I'm trying to import some chunks from other worlds into my Minecraft 1.14 custom map world but every time I try to import it freezes when the blue bar is about to reach the end. 
If I click cancel then it lets me continue using the program but doesn't import the chunks. I've tried with different settings but no matter what I do it doesn't work. I've tested importing chunks to other worlds and there seems to be no problem.

**Comment by Querz** [comment]
What options do you use to import the chunks (offset, overwrite, apply to selection only)?

What Minecraft version was used to generate the world you try to import?

Can you give an approximation of how many chunks / regions you try to import?

Is there an error in the console when you enable debug mode in the settings?

**Comment by BenplayerX** [comment]
When importing I used the offset and marked the overwrite option. I didn't use apply to selection only in most of my attempts tho I did try to activate it a couple of times to see if it helped.

The world was generated in Minecraft 1.12

It's approximately 2 regions.

No, there doesn't seem to be an error in the console when I activate debug mode.

**Comment by Querz** [comment]
It appeared to be a bug with displaying the progress bar when importing chunks with an odd offset (not divisible by 32). It will be fixed in the next release.
The chunks were most likely still imported, you can clear the cache to check.

**Comment by Querz** [comment]
The bug with the progress bar not updating correctly should be fixed in [release 1.9.4](https://github.com/Querz/mcaselector/releases/tag/1.9.4), let me know if there are still problems.
