### ISSUE TITLE
Deprecated Gradle features

### ISSUE THREAD

**Issue by bkinbkin** [Querz/mcaselector#70]
I'm getting a failed build with the reason below returned after gradlew.bat build minifyCss shadowJar

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.

Is there a way for me to work around this restraint?

**Comment by Querz** [comment]
This project is using Gradle 5.5.1, not Gradle 6.0. This warning only indicates that those features _will_ be deprecated in 6.0. Make sure to use the gradle wrapper in this project to build.
