### ISSUE TITLE
Add "Invert Selection" to "Selection" menu

### ISSUE THREAD

**Issue by Fixer-007** [Querz/mcaselector#72]
Sometimes you want to invert your selection ;)

**Comment by Querz** [comment]
Good idea, though this tool is mainly meant to crop huge worlds. Imagine a world that has a total size of 15GB, and you want to delete everything except your base and a radius of 10 chunks around it. It would be way faster to just select those chunks and export them, then replace all region files with the exported files.

Each region is loaded into memory and depending on the visibility and the chunks selected that region uses different amounts of memory. A region that is completely visible has the image of the region, a pre-rendered overlay image of the selected chunks and the data associated with the selected chunks. When a chunk is selected, its coordinates are stored in memory, for up to 1023 chunks per region. When the entire region is selected, all that data is scrapped and just the information that the entire region is selected is stored.

Inverting a selection properly would mean going through every single region file, finding out which chunk exists and then storing this information in memory. A world with a size of 15GB has (based on my experience) approximately 5000 region files, meaning it would need to load 5000 region files and store the information, that a chunk exists, in memory for every single one of them.

What I want to say is this: Inverting a selection makes total sense if you have a clear outline of what you want to invert. It just doesn't really work though if there is no clear outline.

Keep in mind that "inverting a selection" can already be achieved by inverting the filter parameters or by exporting the selected chunks when you want to delete.
