### ISSUE TITLE
"Filter chunks" dropdown is not displayed in full

### ISSUE THREAD

**Issue by Fixer-007** [Querz/mcaselector#73]
![зображення](https://user-images.githubusercontent.com/16494741/73125752-0e4f5f00-3fb3-11ea-8392-fb677b8d459b.png)

Win7, java 8

**Comment by Querz** [comment]
Seems like the other dropdown items are still there, but the scroll bar is not displayed. If you scroll using your mouse wheel or track pad it does scroll down.

I will add the scroll bar back to make it clear that this dropdown is scroll-able.

**Comment by Querz** [comment]
Fixed in (https://github.com/Querz/mcaselector/releases/tag/1.9.4), the dropdown now has a scroll bar to make it clear that it can be scrolled.
