### ISSUE TITLE
Exporting End spawn chunks causes the whole region to go blank if custom terrain was present

### ISSUE THREAD

**Issue by OverFloyd** [Querz/mcaselector#81]
So I had custom terrain in the End and I wanted to paste the end island from my main world, but apparently this deletes the whole region and the custom generation appears at the end of the regions with hard borders. This doesn't happen if I were to paste it in the nether or overworld

**Comment by Querz** [comment]
@OverFloyd Do you mind uploading a screenshot of the problem?

**Comment by OverFloyd** [comment]
Sure.
Terrain I have
![1](https://user-images.githubusercontent.com/46049254/76655305-47e12700-656d-11ea-8ef0-e08b73b153f7.PNG)

The chunks I want to export and import in the world
![2](https://user-images.githubusercontent.com/46049254/76655311-49125400-656d-11ea-96a6-9530d3c23f28.PNG)

What actually happens
![3](https://user-images.githubusercontent.com/46049254/76655313-49aaea80-656d-11ea-8001-3fdf8104c596.PNG)

**Comment by Querz** [comment]
Thanks for the screenshots.
Unfortunately I could not reproduce this issue by doing the following:
* Select the end island chunks in a freshly generated end dimension (20w11a)
* Export selected chunks to a separate folder
* Open other end other world
* Import exported end island into that world

I could not reproduce this by either importing into another end dimension with an offset or into the overworld.

What settings did you select when importing the chunks?

**Comment by OverFloyd** [comment]
I didn't touch anything in the settings.

Here's what I did: selected the main end island from world1 and exported into DIM1 in world2 which had custom terrain. I think it only happens when there's custom terrain tbh

**Comment by Querz** [comment]
I do not guarantee for modded custom terrain, but custom terrain without mods should work fine. Is it possible for you to send a few region files from that custom terrain so i can have a look at them?

**Comment by Querz** [comment]
Due to the lack of a response I assume this is resolved now. If not, feel free to reply to this issue :)
