### ISSUE TITLE
Found Invalid Structure Reference spam

### ISSUE THREAD

**Issue by B-Knight49** [Querz/mcaselector#83]
Using 1.9.3.
About 2 months ago I moved a large chunk of our world a couple thousand chunks South. Since then, whenever a player loads a part of the world that was copied that contains a structure, we get console spam like this all within a couple of seconds:

`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1374, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1374, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1370, -1] ] for chunk [-1374, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1373, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1373, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1370, -1] ] for chunk [-1373, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1372, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1372, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1370, -1] ] for chunk [-1372, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1371, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1371, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1370, -1] ] for chunk [-1371, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1370, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1370, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1370, -1] ] for chunk [-1370, 32883].`
`Found invalid structure reference [ Mineshaft @ [-1372, -1] ] for chunk [-1369, 32883].`

Along with that, we get a severe spike in CPU-usage and, if we encounter it too quickly through, for example, /speed, the server can actually crash. 

All I had done was exported a selection of chunks and then reimported them in the same world with my specified offset. I did not, however, remove the original chunks. They are still there but no longer accessible because of a world border. 

Any advice?

**Comment by Querz** [comment]
This might be a problem with how Minecraft keeps track of Structures. They are saved in the mca files alongside the world data, but with newer versions they seem to be also saved separately in mca files just for this purpose, see [Minecraft Wiki](https://minecraft.gamepedia.com/Java_Edition_level_format#poi_format).
Importing chunks with an offset currently only updates coordinates of structures in the world files.

I'm working on a way to specify an input and output `poi` folder when importing chunks that will also update those files. This will also have to apply for chunk deletion and export.

**Comment by B-Knight49** [comment]
Is there anything you could suggest I do now to fix it? Or is this something I should just wait for? 

I'm fine waiting for your update if need be. Take your time, no rush.

**Comment by Querz** [comment]
I did some more research regarding this problem. It was not caused by not updating the `poi`-files, but actually a bug in calculating the offset for structure references in the world files.

I compiled a snapshot version of 1.9.5 that you can use where this problem is fixed:

[mcaselector-1.9.5-snapshot-all.jar.zip](https://github.com/Querz/mcaselector/files/4394624/mcaselector-1.9.5-snapshot-all.jar.zip)

**Comment by B-Knight49** [comment]
I appreciate you fixing it but, sadly, that won't work for me. The map has been heavily edited since I migrated it South 2 months ago and I can't import the chunks again otherwise all the recent changes will be lost. 

It'd be incredible if you actually implemented an option to fix it directly from within the program though. I program plugins, nothing to do with the chunk formatting, so I don't even know if that's possible but I thought I'd ask.

**Comment by Querz** [comment]
I added an (undocumented) feature that you can use in headless mode to set the structure references to the current chunk location, which gets rid of the `Found invalid structure reference` console spam. The references are only used when generating a structure, so changing them in already generated chunks should be fine.
To use that feature, do the following:
* Open the world in MCA Selector
* Select the chunks that have been imported
* Use `Selection`-->`Export Selection` to export the selection
* Close MCA Selector
* Open a console and run MCA Selector in headless mode with the following command: `java -jar mcaselector-1.9.5.jar --headless --mode change --query "FixStructureReferences = true" --world "path/to/region/folder/" --input "path/to/selection.csv"`

Don't forget to backup your world before doing any changes, as always.

**Comment by B-Knight49** [comment]
Forgive me mate, been really busy. Keep meaning to get around to testing this but am either forgetting or don't have time. Doesn't help that our world file is ~9GB. 

I'll definitely try it soon. Thanks for adding that feature though, I appreciate it.

**Comment by B-Knight49** [comment]
Hey mate, you mention this:

> The references are only used when generating a structure, so changing them in already generated chunks should be fine.

Does that mean it'd be a poor idea to select regions that haven't been previously generated? The sheer number of chunks that we moved would be tedious to manually highlight individually without selecting ungenerated chunks. Would it be a bad thing if I attempted to fix structure references in ungenerated regions or would it naturally overlook and ignore areas not generated?

**Comment by Querz** [comment]
Chunks that are not generated (do not exist) won't be touched.

**Comment by B-Knight49** [comment]
Yup, managed to get it sorted. Took me almost 10 hours (awful upload speeds + transfer errors) but the server seems to be good. I'll close since I'm certain everything's fixed now. Will reopen if we encounter any problems. Appreciate it mate.

Just quickly though; if I select a chunk and press "Edit Chunk", go to the structures and then "Started" (IIRC), it still says id=INVALID after fixing them. I'm not concerned since the messages are gone but thought I'd let you know.

**Comment by Querz** [comment]
@B-Knight49 `Starts` is used to track structures that still need to be generated. After they are done generating, their `id` field is set to `INVALID` by the game and all other fields are deleted. Have a look at the [Wiki](https://minecraft.gamepedia.com/Chunk_format#NBT_structure) at `Structures-->Starts` for more info.

**Comment by B-Knight49** [comment]
Gotcha, nice. Once again, appreciate it.
