### ISSUE TITLE
Question: Can this be used to edit chunks as well?

### ISSUE THREAD

**Issue by Zitchas** [Querz/mcaselector#9]
I'm just curious as to whether or not this could be used to change the biome of a particular chunk. Not regenerate the terrain or anything, just change it (primarily to affect which mobs spawn in an area).

Thank you!

**Comment by Querz** [comment]
The purpose of this tool is to delete or export chunks quickly and on a large scale and even though you can filter chunks by block-level data (e.g. the "Palette" filter), it is not intended to change data on the block level.
There are tools that are far more precise in doing what you are asking for, like WorldEdit or MCEdit.
