### ISSUE TITLE
Font glitch

### ISSUE THREAD

**Issue by Chill-XD** [Querz/mcaselector#91]
I downloaded it updated java and i don't know why is the font like this how do i fix it?

![screenshot 621](https://user-images.githubusercontent.com/53449152/79046751-c3dd9600-7c23-11ea-8c1b-c4806d667ade.png)

**Comment by Querz** [comment]
What version of Java are you using?
Did you select any specific language in the Settings?

**Comment by Chill-XD** [comment]
> What version of Java are you using?
1.9.8
> Did you select any specific language in the Settings?
No it started like this
Sorry for the late reply i was busy

**Comment by Querz** [comment]
Sorry, but "the latest version" is not a version. This information is prone to change very quickly :)

Does this error still occur after redownloading MCA Selector?

**Comment by Chill-XD** [comment]
yes redownloaded mca and reinstalled java (jre-8u241) and uninstalled prev version

**Comment by Querz** [comment]
I'm sorry, but i can't reproduce this error.
What language is your computer set to? Are you using any custom font on your computer?

**Comment by Querz** [comment]
I assume that you resolved this somehow. If so, please share what the problem was so others who have the same problem can fix it too. Also I might be able to make adjustments that this doesn't happen again.
In this case, please reply to this issue :)
