### ISSUE TITLE
I can't open new maps

### ISSUE THREAD

**Issue by promonsami** [Querz/mcaselector#92]
I installed it, and I tried to put a map in, but when I press open after choosing the map nothing happens, it just stays the same way.
What can it be?

**Comment by Querz** [comment]
Does the folder you try to open contain amy .mca files?
If so, what Minecraft version did you use to generate this world? What Java version are you using? What OS are you running?

What exactly do I need to do to reproduce this behaviour?

**Comment by promonsami** [comment]
Yes, there are some .mca files.
The version was 1.12.2. La version de Java es: Versión 8 Actualización 231.
OS version, Catalina 10.15.3

What can I do to fix the problem?

**Comment by Querz** [comment]
Let's first figure out what the problem actually is.

When you open the world, does the map view stay grey or does it turn black?
Are you using any mods in this world?

Also please send the debug.log file. You can create a debug.log file with the following steps:
* Open MCA Selector
* Enable "Print debug messages" in "File"-->"Settings"
* Open the world and wait a few seconds
* Close MCA Selector
There should be a file called "debug.log" now next to the mcaselector.jar. Upload this file **before** opening MCA Selector again.

**Comment by promonsami** [comment]
It stays grey, nothing changes. It looks like I haven't press anything. 
Yes, I am using quite a few mods in the world, could that be a problem?

Nothing really comes up in the debug.log
[debug.log](https://github.com/Querz/mcaselector/files/4488398/debug.log)

Let me know what else I can do

Thank you

**Comment by Querz** [comment]
Running 1.12.2 with mods might indeed be the issue. Do you by any chance run a mod like "JustEnoughIDs"?

**Comment by promonsami** [comment]
Yes, We use Just enough Items

**Comment by promonsami** [comment]
Is there any way of fixing it and using it?
I just want to delete some parts of the world to regenerate it

**Comment by Querz** [comment]
JustEnoughIDs makes some significant changes to how chunks are saved in 1.12.2.
Even though claiming they're "[...] using the 1.13 chunk format in 1.12", they are clearly not.

1.13 uses a true blockstate palette where every blockstate is defined inside the world file. JeIDs only references to a list of internal IDs. There is no way to know the blockstates based on the id that JeID saves in the world file, and the MCA Selector needs those to determine the color of those blocks.

I'm sorry, but I can't really do anything about that.
