### ISSUE TITLE
Headless mode will not export poi regions

### ISSUE THREAD

**Issue by MaveTheMaverick** [Querz/mcaselector#94]
**Describe the bug**
Using headless mode on the command line I am able to export chunks from the region folder but not the poi folder while I am able to do both in the GUI
The debug output doesn't show any type of errors on the log for the poi mca file but it's just not in the directory it's exported to

**To Reproduce**
1. Export region r.0.0.mca
`java -jar mcaselector-1.9.9.jar --headless --debug --mode export --world "C:\[filePath]\server\world\region" --output "C:\[other filePath]\regions\0.0\region" --query "xPos >= 0 AND xPos <= 31 AND zPos >= 0 AND zPos <= 31"`
2. Export poi r.0.0.mca
`java -jar mcaselector-1.9.9.jar --headless --debug --mode export --world "C:\[filePath]\server\world\poi" --output "C:\[other filePath]\regions\0.0\poi" --query "xPos >= 0 AND xPos <= 31 AND zPos >= 0 AND zPos <= 31"`

**Expected behavior**
Expected region r.0.0.mca to be exported my region folder and poi r.0.0.mca to be exported to the adjacent poi folder but the poi did not appear in file explorer afterward

**Screenshots and other files**
Working export of region r.0.0.mca
[debug_regions_export.txt](https://github.com/Querz/mcaselector/files/4494764/debug_regions_export.txt)
Not Working export of poi r.0.0.mca
[debug_poi_export.txt](https://github.com/Querz/mcaselector/files/4494765/debug_poi_export.txt)

Original region r.0.0.mca and poi r.0.0.mca that I'm trying to export:
[world.zip](https://github.com/Querz/mcaselector/files/4494829/world.zip)

**Environment:**
- OS: Windows 10
- Java version: 1.8.0_221
- Version 1.9.9

**Additional context**
Add any other context about the problem here, e.g.:
- Minecraft version: [paperMC](https://papermc.io/) server build 184 running 1.15.2 w/ no mods
- Previously used mcaselector to import these chunks into this world via GUI

Edit: I'm not sure if there is any particularly useful/necessary data in the poi regions so it is most likely not a major issue

**Comment by Querz** [comment]
The MCA files in the `poi` folder have a different format than the files saved in the `region` folder (see [Wiki](https://minecraft.gamepedia.com/Java_Edition_level_format#poi_format)), that's why the filters don't work on them. Currently, they only serve the purpose of saving villager's targets (like homes and working places).

I will look into whether those files are actually relevant for exporting or whether they can be ignored and Minecraft will fix them by itself when data is missing or they don't match the world.

**Comment by Querz** [comment]
It looks like Minecraft checks whether the data in the poi files is actually valid and matches the blocks in the world. It should be safe to ignore them.
